'use strict';
/**
 * lib/lavorazioniSchede.js — F-261 (AUDIT.md del frontend), passo 1.
 *
 * Schede lavorazione: per ogni lavorazione PERICOLOSA, rischi con P×D,
 * misure, DPI con norma, attrezzature con verifica, formazione richiesta,
 * norme di riferimento e le due frasi del carosello sicurezza in timbratura.
 *
 * Perché esiste: il vecchio catalogo (lib/lavorazioniCatalog.js) è solo un
 * elenco di nomi e la Sezione 5 del POS viene inventata dall'AI a ogni POS.
 * Queste schede sono la fonte unica che POS, Ladia e carosello leggeranno.
 *
 * STATO: tutte le schede sono `revisione: "bozza"`. Prima di presentarle
 * come verificate le deve rileggere una persona competente (RSPP/CSE).
 * Anche i codici ISO 7010 dei cartelli vanno confermati in revisione.
 *
 * Dati puri: nessun require, nessun I/O. Lo legge anche la timbratura
 * (carosello), quindi non deve mai poter lanciare né rallentare.
 */

// ── DPI ──────────────────────────────────────────────────────────────────────
const DPI = {
  casco:            { nome: "Elmetto di protezione", norma: "UNI EN 397" },
  casco_dielettrico:{ nome: "Elmetto isolante per lavori elettrici", norma: "UNI EN 50365" },
  scarpe:           { nome: "Calzature di sicurezza S3", norma: "UNI EN ISO 20345" },
  stivali:          { nome: "Stivali di sicurezza S5", norma: "UNI EN ISO 20345" },
  gilet:            { nome: "Indumenti ad alta visibilità", norma: "UNI EN ISO 20471" },
  guanti:           { nome: "Guanti contro rischi meccanici", norma: "UNI EN 388" },
  guanti_chimici:   { nome: "Guanti contro agenti chimici", norma: "UNI EN ISO 374-1" },
  guanti_calore:    { nome: "Guanti contro il calore", norma: "UNI EN 407" },
  guanti_dielettrici:{ nome: "Guanti isolanti", norma: "CEI EN 60903" },
  occhiali:         { nome: "Occhiali di protezione", norma: "UNI EN 166" },
  visiera:          { nome: "Visiera di protezione", norma: "UNI EN 166" },
  maschera_saldatura:{ nome: "Maschera per saldatura con filtro", norma: "UNI EN 175 / UNI EN 169" },
  otoprotettori:    { nome: "Otoprotettori (cuffie o inserti)", norma: "UNI EN 352" },
  ffp2:             { nome: "Facciale filtrante FFP2", norma: "UNI EN 149" },
  ffp3:             { nome: "Facciale filtrante FFP3", norma: "UNI EN 149" },
  semimaschera_a:   { nome: "Semimaschera con filtri per vapori organici (A2P3)", norma: "UNI EN 140 / UNI EN 14387" },
  autorespiratore:  { nome: "Autorespiratore o respiratore isolante", norma: "UNI EN 137 / UNI EN 14593" },
  imbracatura:      { nome: "Imbracatura anticaduta", norma: "UNI EN 361" },
  cordino:          { nome: "Cordino con assorbitore di energia", norma: "UNI EN 355" },
  retrattile:       { nome: "Dispositivo anticaduta retrattile", norma: "UNI EN 360" },
  tuta_monouso:     { nome: "Tuta monouso tipo 5/6", norma: "UNI EN ISO 13982-1 / UNI EN 13034" },
  abiti_saldatura:  { nome: "Indumenti per saldatura", norma: "UNI EN ISO 11611" },
  abiti_calore:     { nome: "Indumenti contro calore e fiamma", norma: "UNI EN ISO 11612" },
  ginocchiere:      { nome: "Ginocchiere", norma: "UNI EN 14404" },
};

// ── Formazione e abilitazioni ────────────────────────────────────────────────
const FORMAZIONE = {
  base:               "Formazione generale e specifica dei lavoratori (art. 37)",
  preposto:           "Preposto presente durante la lavorazione (art. 19)",
  ponteggi:           "Addetti al montaggio e smontaggio dei ponteggi (Allegato XXI)",
  anticaduta:         "Addestramento all'uso dei DPI anticaduta di III categoria (art. 77)",
  ple:                "Abilitazione all'uso di piattaforme di lavoro elevabili (art. 73 c.5)",
  gru_torre:          "Abilitazione gru a torre (art. 73 c.5)",
  autogru:            "Abilitazione gru mobili / autogru (art. 73 c.5)",
  sollevatore:        "Abilitazione carrelli elevatori e sollevatori telescopici (art. 73 c.5)",
  mmt:                "Abilitazione escavatori, pale e terne (art. 73 c.5)",
  pompa_cls:          "Abilitazione pompe per calcestruzzo (art. 73 c.5)",
  spazi_confinati:    "Formazione e addestramento spazi confinati (D.P.R. 177/2011)",
  amianto:            "Corso operatori amianto (art. 258, D.P.R. 8/8/1994)",
  pes_pav:            "Persona esperta o avvertita per lavori elettrici (CEI 11-27)",
  segnaletica:        "Addetti segnaletica stradale (D.I. 22/01/2019)",
  antincendio:        "Addetto antincendio presente in cantiere",
  primo_soccorso:     "Addetto primo soccorso presente in cantiere",
  montatori_gru:      "Montatori gru: formazione specifica del fabbricante",
};

// ── Categorie ────────────────────────────────────────────────────────────────
const CATEGORIE = [
  { id: "quota",       nome: "Lavori in quota" },
  { id: "scavi",       nome: "Scavi e fondazioni" },
  { id: "demolizioni", nome: "Demolizioni e rimozioni" },
  { id: "strutture",   nome: "Strutture" },
  { id: "sollevamenti",nome: "Sollevamenti e mezzi" },
  { id: "caldo_chimico", nome: "Lavori a caldo e prodotti chimici" },
  { id: "elettrico",   nome: "Rischio elettrico" },
  { id: "altri",       nome: "Altre lavorazioni a rischio" },
];

// Cartelli del carosello: divieto (cerchio rosso), obbligo (cerchio blu),
// pericolo (triangolo giallo). Codici ISO 7010 da confermare in revisione.
const TIPI_CARTELLO = ["divieto", "obbligo", "pericolo"];

// Formato compatto: rischi [descrizione, P, D]; attrezzature [nome, verifica].
const SCHEDE = [
  // ══ LAVORI IN QUOTA ══════════════════════════════════════════════════════
  {
    id: "ponteggio-montaggio",
    nome: "Montaggio, trasformazione e smontaggio del ponteggio",
    categoria: "quota", pericolosita: "alta",
    descrizione: "Montaggio, modifica e smontaggio di ponteggio metallico fisso secondo il PiMUS, da parte di squadra formata e sotto la sorveglianza di un preposto.",
    fasi: ["Verifica del piano di appoggio e posa delle basette", "Montaggio a piani successivi con ancoraggi alla facciata", "Posa di impalcati, parapetti e fermapiede", "Smontaggio in ordine inverso con calo controllato degli elementi"],
    rischi: [["Caduta dall'alto durante il montaggio", 3, 4], ["Caduta di elementi metallici su persone sotto", 3, 4], ["Crollo per ancoraggi insufficienti o appoggio cedevole", 2, 4], ["Movimentazione manuale di tubi e tavole", 3, 2], ["Contatto con linee elettriche aeree", 1, 4]],
    misure: ["Montaggio solo secondo il PiMUS e lo schema del libretto ministeriale", "Squadra con formazione specifica e preposto sempre presente", "Imbracatura agganciata in ogni fase, anche nei passaggi di piano", "Area sottostante delimitata e interdetta al passaggio", "Ancoraggi alla facciata posati man mano, mai a montaggio finito", "Calo degli elementi con carrucola o argano, mai lanciati", "Verifica di distanze da linee elettriche prima di iniziare", "Sospendere con vento forte o pioggia"],
    dpi: ["casco", "scarpe", "guanti", "imbracatura", "cordino", "gilet"],
    attrezzature: [["Ponteggio metallico fisso", "Autorizzazione ministeriale, libretto, PiMUS e verifica elementi prima del montaggio (Allegato XIX)"], ["Argano o carrucola", "Verifica funi e ganci prima dell'uso"]],
    formazione: ["ponteggi", "anticaduta", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 131-138", "Allegati XVIII, XIX, XXI, XXII (PiMUS)"],
    carosello: { cartello: { tipo: "divieto", iso7010: "P004" }, pericolo: "Possono cadere tubi e attrezzi.", regola: "Non passare sotto." },
    sostituisce: ["Montaggio ponteggio"],
  },
  {
    id: "ponteggio-uso",
    nome: "Lavori sul ponteggio",
    categoria: "quota", pericolosita: "alta",
    descrizione: "Lavorazioni eseguite dagli impalcati di un ponteggio già montato e verificato: facciate, intonaci, cappotto, tinteggiature, posa di elementi.",
    fasi: ["Controllo visivo del ponteggio prima di salire", "Accesso dalle scale interne del ponteggio", "Lavorazione dagli impalcati", "Pulizia degli impalcati a fine turno"],
    rischi: [["Caduta dall'alto per parapetti rimossi o mancanti", 2, 4], ["Caduta di materiali e attrezzi verso il basso", 3, 3], ["Scivolamento sugli impalcati", 3, 2], ["Sovraccarico degli impalcati", 2, 4]],
    misure: ["Mai rimuovere parapetti, fermapiede o tavole: le modifiche le fa solo la squadra del ponteggio", "Accesso solo dalle scale del ponteggio, mai arrampicandosi", "Non accumulare materiale oltre il carico indicato", "Teli o reti contro la caduta di materiale verso strada e passaggi", "Impalcati sgombri e puliti", "Controllo del preposto dopo vento forte, pioggia o lunghe pause"],
    dpi: ["casco", "scarpe", "guanti", "gilet"],
    attrezzature: [["Ponteggio metallico fisso", "Verifica dopo eventi meteo e interruzioni prolungate (art. 137)"]],
    formazione: ["base", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 122, 126, 137, 138"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W008" }, pericolo: "Dal ponteggio si cade.", regola: "Non togliere mai i parapetti." },
    sostituisce: [],
  },
  {
    id: "trabattello",
    nome: "Lavori su trabattello",
    categoria: "quota", pericolosita: "alta",
    descrizione: "Lavori su ponte su ruote (trabattello) montato secondo il manuale del fabbricante.",
    fasi: ["Montaggio secondo il manuale", "Blocco delle ruote e livellamento", "Lavoro dall'impalcato con parapetti", "Spostamento solo senza persone sopra"],
    rischi: [["Ribaltamento del trabattello", 2, 4], ["Caduta dall'alto", 2, 4], ["Spostamento accidentale per ruote non bloccate", 3, 3], ["Caduta di attrezzi", 3, 2]],
    misure: ["Montaggio solo secondo il manuale, con stabilizzatori se previsti", "Ruote bloccate prima di salire", "Mai spostarlo con persone o materiale sopra", "Piano di appoggio piano e resistente", "Parapetti completi sull'impalcato di lavoro", "Non usare oltre l'altezza massima indicata, all'esterno valutare il vento"],
    dpi: ["casco", "scarpe", "guanti"],
    attrezzature: [["Trabattello", "Conforme UNI EN 1004, verifica componenti prima del montaggio"]],
    formazione: ["base", "anticaduta"],
    norme: ["D.Lgs. 81/08 art. 140", "UNI EN 1004"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W001" }, pericolo: "Il trabattello si ribalta.", regola: "Blocca le ruote prima di salire." },
    sostituisce: [],
  },
  {
    id: "ple",
    nome: "Lavori con piattaforma elevabile (PLE)",
    categoria: "quota", pericolosita: "alta",
    descrizione: "Lavori in quota dal cestello di una piattaforma di lavoro mobile elevabile (a pantografo, articolata o su autocarro).",
    fasi: ["Controllo della macchina e del terreno", "Posizionamento e stabilizzazione", "Salita con imbracatura agganciata", "Lavoro e discesa controllata"],
    rischi: [["Ribaltamento per terreno cedevole o stabilizzatori non estesi", 2, 4], ["Caduta o sbalzo dal cestello", 2, 4], ["Schiacciamento contro strutture sopra il cestello", 2, 4], ["Contatto con linee elettriche aeree", 1, 4], ["Investimento di persone a terra", 2, 3]],
    misure: ["Uso solo da operatore abilitato", "Terreno verificato e stabilizzatori sempre estesi se previsti", "Imbracatura agganciata al punto di ancoraggio del cestello", "Mai salire sui parapetti del cestello o sporgersi", "Area sotto il cestello delimitata", "Persona a terra in grado di manovrare i comandi di emergenza", "Distanze di sicurezza dalle linee elettriche (Allegato IX)", "Non usare con vento oltre il limite del fabbricante"],
    dpi: ["casco", "scarpe", "imbracatura", "cordino", "gilet"],
    attrezzature: [["Piattaforma di lavoro elevabile", "Verifiche periodiche (Allegato VII) e controllo giornaliero"]],
    formazione: ["ple", "anticaduta"],
    norme: ["D.Lgs. 81/08 artt. 71, 73", "Allegato VII"],
    carosello: { cartello: { tipo: "obbligo", iso7010: "M018" }, pericolo: "Dal cestello si può cadere.", regola: "Aggancia l'imbracatura." },
    sostituisce: [],
  },
  {
    id: "scale-portatili",
    nome: "Lavori su scale portatili",
    categoria: "quota", pericolosita: "media",
    descrizione: "Uso di scale portatili per accessi e lavori brevi, solo quando non sono possibili attrezzature più sicure.",
    fasi: ["Scelta della scala adatta", "Posizionamento stabile", "Salita e lavoro con tre punti di appoggio", "Discesa"],
    rischi: [["Caduta dalla scala", 3, 3], ["Scivolamento o ribaltamento della scala", 2, 3], ["Caduta di attrezzi su chi è sotto", 2, 2]],
    misure: ["Usare la scala solo per lavori brevi e a basso rischio", "Scala conforme, con piedini antiscivolo, in buono stato", "Scala a pioli che sporge almeno 1 m oltre l'appoggio di sbarco", "Mai salire con carichi in mano: attrezzi in borsa", "Mai sull'ultimo gradino della scala doppia", "Un collega trattiene la scala se non è vincolata"],
    dpi: ["casco", "scarpe"],
    attrezzature: [["Scala portatile", "Conforme UNI EN 131, controllo visivo prima dell'uso"]],
    formazione: ["base"],
    norme: ["D.Lgs. 81/08 art. 113", "UNI EN 131"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W008" }, pericolo: "Dalla scala si cade.", regola: "Sali con le mani libere." },
    sostituisce: [],
  },
  {
    id: "aperture-vuoti",
    nome: "Lavori vicino ad aperture nei solai e vani",
    categoria: "quota", pericolosita: "alta",
    descrizione: "Lavori in prossimità di aperture nei solai, vani scala, vani ascensore, bordi di solai senza tamponamenti.",
    fasi: ["Individuazione delle aperture", "Protezione con parapetti o coperture fissate", "Lavorazione", "Ripristino delle protezioni rimosse"],
    rischi: [["Caduta nel vuoto attraverso aperture", 3, 4], ["Caduta di materiali ai piani inferiori", 3, 3], ["Inciampo su coperture non fissate", 2, 2]],
    misure: ["Ogni apertura protetta con parapetto o copertura fissata e segnalata", "Coperture resistenti al carico e bloccate contro lo spostamento", "Chi rimuove una protezione la rimette prima di andare via", "Bordi dei solai protetti fino alla posa dei tamponamenti", "Dove non si può proteggere: imbracatura agganciata a punto sicuro"],
    dpi: ["casco", "scarpe", "imbracatura", "cordino"],
    attrezzature: [["Parapetti provvisori", "Conformi UNI EN 13374, verifica fissaggi"]],
    formazione: ["base", "anticaduta"],
    norme: ["D.Lgs. 81/08 art. 146"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W008" }, pericolo: "Dai buchi nel solaio si cade.", regola: "Non togliere le protezioni." },
    sostituisce: [],
  },
  {
    id: "coperture-lavori",
    nome: "Lavori su coperture",
    categoria: "quota", pericolosita: "alta",
    descrizione: "Rifacimento, manutenzione e posa di manti di copertura (tegole, coppi, lamiera, guaine), lattonerie, gronde e linee vita.",
    fasi: ["Verifica della portata e dei bordi", "Allestimento di parapetti o linea vita", "Rimozione e posa del manto", "Lattonerie e chiusure"],
    rischi: [["Caduta dal bordo della copertura", 3, 4], ["Scivolamento su falde inclinate o bagnate", 3, 3], ["Caduta di materiali verso il basso", 3, 3], ["Movimentazione di carichi in posizioni scomode", 3, 2], ["Esposizione al sole e al caldo", 3, 2]],
    misure: ["Protezione dei bordi con parapetti o ponteggio a quota gronda", "Dove manca: linea vita e imbracatura sempre agganciata", "Sollevamento materiali con montacarichi o gru, mai a mano su scale", "Area sottostante delimitata", "Sospendere con pioggia, ghiaccio o vento forte", "Pause e acqua nelle ore calde"],
    dpi: ["casco", "scarpe", "guanti", "imbracatura", "cordino"],
    attrezzature: [["Linea vita provvisoria o permanente", "Conforme UNI EN 795, verifica di installazione"], ["Montacarichi", "Verifica periodica"]],
    formazione: ["base", "anticaduta", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 111, 115, 148"],
    carosello: { cartello: { tipo: "obbligo", iso7010: "M018" }, pericolo: "Dal tetto si cade.", regola: "Aggancia sempre la linea vita." },
    sostituisce: ["Copertura in tegole", "Copertura in coppi", "Copertura piana", "Copertura in lamiera", "Copertura in legno", "Isolamento copertura", "Canali di gronda", "Pluviali", "Predisposizione linee vita", "Linee vita permanenti"],
  },
  {
    id: "coperture-fragili",
    nome: "Lavori su coperture fragili (lucernari, fibrocemento, lastre)",
    categoria: "quota", pericolosita: "alta",
    descrizione: "Lavori su o vicino a superfici non portanti: lastre in fibrocemento, lastre traslucide, lucernari, coperture in lamiera di spessore non verificato.",
    fasi: ["Accertamento della resistenza della copertura", "Posa di passerelle o reti sotto", "Lavorazione dai camminamenti", "Rimozione dei camminamenti"],
    rischi: [["Sfondamento della lastra e caduta nel vuoto", 3, 4], ["Caduta dal bordo", 2, 4], ["Esposizione ad amianto in lastre vecchie", 2, 4]],
    misure: ["Prima di salire accertare la resistenza (art. 148)", "Mai camminare direttamente sulle lastre: solo passerelle", "Reti anticaduta o impalcati sotto la copertura", "Lucernari protetti con griglie o parapetti", "Lastre di epoca incerta: verificare l'amianto prima di toccarle"],
    dpi: ["casco", "scarpe", "imbracatura", "cordino"],
    attrezzature: [["Passerelle di ripartizione", "Verifica portata e fissaggio"], ["Reti anticaduta", "Conformi UNI EN 1263"]],
    formazione: ["base", "anticaduta", "preposto"],
    norme: ["D.Lgs. 81/08 art. 148"],
    carosello: { cartello: { tipo: "divieto", iso7010: "P024" }, pericolo: "La lastra si sfonda.", regola: "Non camminare sulle lastre." },
    sostituisce: ["Lucernari e abbaini"],
  },
  {
    id: "fotovoltaico",
    nome: "Installazione di impianto fotovoltaico",
    categoria: "quota", pericolosita: "alta",
    descrizione: "Posa di strutture e moduli fotovoltaici in copertura e collegamenti elettrici in corrente continua e alternata.",
    fasi: ["Allestimento protezioni in copertura", "Posa delle strutture di fissaggio", "Sollevamento e posa dei moduli", "Cablaggio e allaccio all'inverter"],
    rischi: [["Caduta dall'alto dalla copertura", 3, 4], ["Elettrocuzione: i moduli producono tensione appena esposti alla luce", 2, 4], ["Caduta dei moduli durante il sollevamento", 2, 3], ["Movimentazione di moduli ingombranti", 3, 2]],
    misure: ["Protezioni anticaduta come per i lavori su coperture", "Connettori aperti e cavi isolati: i moduli sono in tensione alla luce", "Collegamenti solo da personale PES/PAV", "Sollevamento dei moduli con mezzi, mai a mano su scale", "Lavorare in coppia nella movimentazione"],
    dpi: ["casco", "scarpe", "guanti", "imbracatura", "cordino", "guanti_dielettrici"],
    attrezzature: [["Montacarichi o sollevatore", "Verifica periodica"]],
    formazione: ["anticaduta", "pes_pav"],
    norme: ["D.Lgs. 81/08 artt. 82, 111, 115", "CEI 11-27"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W012" }, pericolo: "I pannelli danno corrente.", regola: "Non toccare i cavi scoperti." },
    sostituisce: ["Impianto fotovoltaico"],
  },
  {
    id: "ascensore-vano",
    nome: "Installazione di ascensore e montacarichi",
    categoria: "quota", pericolosita: "alta",
    descrizione: "Montaggio di guide, cabina e macchinario all'interno del vano corsa, con lavoro su più livelli.",
    fasi: ["Protezione delle porte di piano", "Montaggio del ponteggio interno o della piattaforma", "Posa di guide e cabina", "Collaudo"],
    rischi: [["Caduta nel vano corsa", 2, 4], ["Caduta di materiali dall'alto nel vano", 3, 4], ["Schiacciamento da cabina o contrappeso in movimento", 2, 4], ["Elettrocuzione durante i collegamenti", 2, 4]],
    misure: ["Porte di piano chiuse con barriere fino alla posa delle porte definitive", "Nessun lavoro sovrapposto nello stesso vano", "Imbracatura agganciata a punto sicuro quando si lavora sul bordo", "Movimentazione della cabina solo con comando controllato", "Collegamenti elettrici a impianto sezionato"],
    dpi: ["casco", "scarpe", "guanti", "imbracatura", "cordino"],
    attrezzature: [["Paranco di montaggio", "Verifica funi e freni"]],
    formazione: ["base", "anticaduta", "pes_pav"],
    norme: ["D.Lgs. 81/08 art. 146", "D.P.R. 162/1999"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W008" }, pericolo: "Nel vano si cade nel vuoto.", regola: "Non sporgerti nel vano." },
    sostituisce: ["Ascensore", "Montacarichi", "Installazione ascensore da cantiere"],
  },

  // ══ SCAVI E FONDAZIONI ══════════════════════════════════════════════════
  {
    id: "scavo-sbancamento",
    nome: "Scavo di sbancamento e a sezione aperta con mezzi meccanici",
    categoria: "scavi", pericolosita: "alta",
    descrizione: "Scavi di splateamento e sbancamento con escavatore, con pareti a scarpa e carico del terreno su autocarri.",
    fasi: ["Verifica dei sottoservizi e del terreno", "Tracciamento e delimitazione", "Scavo con pareti a scarpa", "Carico e trasporto del materiale"],
    rischi: [["Franamento delle pareti dello scavo", 3, 4], ["Caduta di persone o mezzi nello scavo", 2, 4], ["Investimento da mezzi in movimento", 3, 4], ["Rottura di sottoservizi (gas, elettricità, acqua)", 2, 4], ["Rumore e vibrazioni", 3, 2]],
    misure: ["Pareti con inclinazione adeguata al terreno o armate", "Ciglio dello scavo delimitato a distanza di sicurezza", "Nessun deposito di terra o materiale sul ciglio", "Nessuna persona nel raggio d'azione dell'escavatore", "Mappatura dei sottoservizi prima di scavare", "Percorsi separati per mezzi e pedoni", "Controllo delle pareti dopo pioggia o gelo"],
    dpi: ["casco", "scarpe", "gilet", "otoprotettori"],
    attrezzature: [["Escavatore", "Verifiche e manutenzione secondo il libretto, controllo giornaliero"]],
    formazione: ["mmt", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 118, 120"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W001" }, pericolo: "Il bordo dello scavo frana.", regola: "Stai lontano dal ciglio." },
    sostituisce: ["Scavo a sezione aperta", "Scavo per fondazioni"],
  },
  {
    id: "scavo-trincea",
    nome: "Scavo a sezione obbligata e trincee",
    categoria: "scavi", pericolosita: "alta",
    descrizione: "Scavi stretti e profondi per fondazioni, reti e condotte, con presenza di persone all'interno dello scavo.",
    fasi: ["Scavo con mezzo meccanico", "Posa delle armature o blindaggi oltre 1,50 m", "Lavoro all'interno dello scavo", "Rinterro e recupero delle armature"],
    rischi: [["Seppellimento per franamento delle pareti", 3, 4], ["Caduta nello scavo", 3, 3], ["Caduta di materiale dal ciglio su chi è dentro", 3, 3], ["Annegamento o asfissia per acqua o gas nello scavo", 1, 4]],
    misure: ["Oltre 1,50 m di profondità: armature o blindaggi prima di entrare (art. 119)", "Mai entrare in uno scavo non armato", "Scale per scendere e risalire ogni 15-20 m", "Parapetti o delimitazione sul ciglio", "Nessun mezzo o carico vicino al ciglio", "Una persona sempre fuori dallo scavo a sorvegliare"],
    dpi: ["casco", "scarpe", "gilet", "stivali"],
    attrezzature: [["Blindaggi per scavi", "Montaggio secondo le istruzioni del fabbricante"]],
    formazione: ["base", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 118, 119, 120, 121"],
    carosello: { cartello: { tipo: "divieto", iso7010: "P001" }, pericolo: "Il terreno può franare.", regola: "Non scendere senza armature." },
    sostituisce: ["Scavo a sezione obbligata", "Travi rovesce"],
  },
  {
    id: "scavo-sottoservizi",
    nome: "Scavi in presenza di sottoservizi",
    categoria: "scavi", pericolosita: "alta",
    descrizione: "Scavi vicino a reti interrate di gas, elettricità, acqua, fognature e telecomunicazioni.",
    fasi: ["Richiesta delle planimetrie agli enti gestori", "Individuazione con cercaservizi", "Scavo a mano in prossimità delle reti", "Protezione delle reti scoperte"],
    rischi: [["Elettrocuzione per rottura di cavi interrati", 2, 4], ["Esplosione o incendio per rottura di condotte gas", 1, 4], ["Allagamento dello scavo per rottura di condotte", 2, 3]],
    misure: ["Planimetrie degli enti gestori prima di iniziare", "Rilievo con cercaservizi e segnatura a terra", "Vicino alle reti: scavo solo a mano o con aspiratore", "Numero di emergenza dell'ente gestore a disposizione", "In caso di rottura: allontanare tutti e chiamare l'ente e il 112"],
    dpi: ["casco", "scarpe", "gilet", "guanti"],
    attrezzature: [["Cercaservizi", "Taratura secondo il fabbricante"]],
    formazione: ["base", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 83, 118"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W012" }, pericolo: "Sotto ci sono gas e corrente.", regola: "Vicino ai tubi scava a mano." },
    sostituisce: ["Scavo per sottoservizi"],
  },
  {
    id: "pali-perforazioni",
    nome: "Pali, micropali e perforazioni",
    categoria: "scavi", pericolosita: "alta",
    descrizione: "Esecuzione di pali, micropali, diaframmi e tiranti con macchine perforatrici, posa delle armature e getto.",
    fasi: ["Posizionamento della perforatrice", "Perforazione", "Posa dell'armatura", "Getto o iniezione"],
    rischi: [["Trascinamento da organi rotanti (aste, eliche)", 2, 4], ["Ribaltamento della macchina", 1, 4], ["Caduta di aste e armature durante il sollevamento", 2, 4], ["Rumore e vibrazioni", 4, 2], ["Caduta in fori aperti", 2, 3]],
    misure: ["Area di lavoro della perforatrice delimitata", "Nessuno vicino alle aste in rotazione", "Terreno di appoggio verificato", "Fori chiusi o protetti appena eseguiti", "Imbracatura delle armature con brache verificate"],
    dpi: ["casco", "scarpe", "guanti", "otoprotettori", "gilet", "occhiali"],
    attrezzature: [["Perforatrice", "Manutenzione e verifiche secondo il libretto"]],
    formazione: ["base", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 71, 118", "Titolo VIII capi II e III"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W001" }, pericolo: "L'asta gira e ti trascina.", regola: "Stai lontano dalla trivella." },
    sostituisce: ["Palificazione", "Micropali", "Diaframmi"],
  },

  // ══ DEMOLIZIONI E RIMOZIONI ═════════════════════════════════════════════
  {
    id: "demolizione-strutture",
    nome: "Demolizione di strutture portanti",
    categoria: "demolizioni", pericolosita: "alta",
    descrizione: "Demolizione di murature portanti, solai, scale, coperture e muri di contenimento secondo un programma delle demolizioni.",
    fasi: ["Verifica delle condizioni dell'opera", "Puntellamenti e distacco degli impianti", "Demolizione dall'alto verso il basso", "Allontanamento delle macerie"],
    rischi: [["Crollo improvviso di parti della struttura", 3, 4], ["Caduta dall'alto dai piani in demolizione", 3, 4], ["Caduta di materiali su chi è sotto", 3, 4], ["Polveri con silice cristallina", 4, 3], ["Rumore e vibrazioni", 4, 2]],
    misure: ["Programma delle demolizioni scritto prima di iniziare (art. 151)", "Demolire dall'alto verso il basso, mai scalzare alla base", "Zona di demolizione delimitata e interdetta", "Puntellamenti delle parti instabili", "Impianti (gas, acqua, elettricità) staccati prima di iniziare", "Bagnare per abbattere le polveri", "Preposto presente per tutta la demolizione"],
    dpi: ["casco", "scarpe", "guanti", "ffp3", "occhiali", "otoprotettori"],
    attrezzature: [["Martello demolitore", "Manutenzione secondo il libretto, valutazione vibrazioni"]],
    formazione: ["base", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 150-156", "Titolo IX capo II (silice cristallina)"],
    carosello: { cartello: { tipo: "divieto", iso7010: "P004" }, pericolo: "Può crollare tutto insieme.", regola: "Non entrare nella zona chiusa." },
    sostituisce: ["Demolizione murature portanti", "Demolizione solai", "Demolizione copertura", "Demolizione scale", "Demolizione muri di contenimento"],
  },
  {
    id: "demolizione-meccanica",
    nome: "Demolizione con mezzi meccanici",
    categoria: "demolizioni", pericolosita: "alta",
    descrizione: "Demolizione con escavatore attrezzato con pinza, martellone o cesoia, compresa la riduzione delle macerie.",
    fasi: ["Delimitazione dell'area di sicurezza", "Demolizione con mezzo meccanico", "Separazione e carico delle macerie"],
    rischi: [["Proiezione di frammenti", 3, 3], ["Crollo incontrollato verso il mezzo o l'area esterna", 2, 4], ["Investimento da parte del mezzo", 2, 4], ["Polveri e rumore", 4, 3]],
    misure: ["Area di sicurezza almeno pari all'altezza dell'opera più un margine", "Nessuno a terra nel raggio del mezzo durante la demolizione", "Cabina del mezzo con protezione FOPS", "Nebulizzazione d'acqua per le polveri", "Segnalatore a terra in contatto con l'operatore"],
    dpi: ["casco", "scarpe", "gilet", "otoprotettori", "ffp3"],
    attrezzature: [["Escavatore con attrezzature da demolizione", "Compatibilità attrezzo-macchina, verifiche periodiche"]],
    formazione: ["mmt", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 150-156"],
    carosello: { cartello: { tipo: "divieto", iso7010: "P004" }, pericolo: "La macchina lancia pezzi.", regola: "Stai fuori dalla zona chiusa." },
    sostituisce: ["Demolizione cordoli e marciapiedi"],
  },
  {
    id: "demolizioni-interne",
    nome: "Demolizioni e rimozioni interne non strutturali",
    categoria: "demolizioni", pericolosita: "media",
    descrizione: "Demolizione di tramezzi, rimozione di pavimenti, rivestimenti, intonaci, controsoffitti e impianti esistenti.",
    fasi: ["Distacco degli impianti", "Demolizione manuale o con piccoli demolitori", "Insacco e allontanamento delle macerie"],
    rischi: [["Polveri con silice cristallina", 4, 3], ["Rumore e vibrazioni da demolitori", 4, 2], ["Tagli e schiacciamenti alle mani", 3, 2], ["Caduta di parti di controsoffitto o intonaco", 2, 2], ["Contatto con impianti elettrici non disattivati", 2, 4], ["Materiali con amianto non individuati (pavimenti vinilici, colle, coibentazioni)", 1, 4]],
    misure: ["Impianti staccati e verificati prima di demolire", "Bagnare e aspirare per ridurre la polvere", "Materiali sospetti di amianto: fermarsi e far verificare", "Pause e rotazione con i demolitori per le vibrazioni", "Macerie allontanate subito, percorsi liberi"],
    dpi: ["casco", "scarpe", "guanti", "ffp3", "occhiali", "otoprotettori"],
    attrezzature: [["Martello demolitore elettrico", "Controllo del cavo e dell'utensile prima dell'uso"]],
    formazione: ["base"],
    norme: ["D.Lgs. 81/08 artt. 150-156", "Titolo VIII capi II e III", "Titolo IX capo II"],
    carosello: { cartello: { tipo: "obbligo", iso7010: "M017" }, pericolo: "La polvere fa male.", regola: "Metti la mascherina." },
    sostituisce: ["Demolizione tramezzi", "Rimozione pavimenti", "Rimozione rivestimenti", "Rimozione intonaci", "Rimozione controsoffitti", "Rimozione serramenti", "Rimozione impianto elettrico", "Rimozione impianto idraulico", "Rimozione impianto di riscaldamento", "Rimozione guaine impermeabilizzanti"],
  },
  {
    id: "taglio-calcestruzzo",
    nome: "Taglio e carotaggio di calcestruzzo e murature",
    categoria: "demolizioni", pericolosita: "alta",
    descrizione: "Taglio con sega a disco, sega a filo diamantato, carotatrice o flessibile su calcestruzzo, laterizio e pietra.",
    fasi: ["Verifica di armature e impianti nella zona", "Puntellamento delle parti che si staccano", "Taglio ad acqua", "Rimozione dei blocchi tagliati"],
    rischi: [["Polvere di silice cristallina", 4, 4], ["Tagli da disco o filo", 2, 4], ["Caduta dei blocchi tagliati", 2, 4], ["Rumore elevato", 4, 3], ["Rottura del disco o del filo con proiezione", 2, 4]],
    misure: ["Taglio sempre ad acqua o con aspirazione alla fonte", "Blocchi da staccare sostenuti prima dell'ultimo taglio", "Protezioni dell'utensile sempre montate", "Area attorno al filo diamantato delimitata", "Verifica di cavi e tubi nascosti prima di tagliare"],
    dpi: ["casco", "scarpe", "guanti", "ffp3", "visiera", "otoprotettori"],
    attrezzature: [["Sega a disco, carotatrice, sega a filo", "Manutenzione secondo il libretto, dischi adatti al materiale"]],
    formazione: ["base", "preposto"],
    norme: ["Titolo IX capo II (silice cristallina)", "Titolo VIII capo II"],
    carosello: { cartello: { tipo: "obbligo", iso7010: "M017" }, pericolo: "La polvere di cemento fa male.", regola: "Taglia sempre con l'acqua." },
    sostituisce: ["Taglio strutture in c.a."],
  },
  {
    id: "aperture-muri-portanti",
    nome: "Apertura di vani in murature portanti con cerchiatura",
    categoria: "demolizioni", pericolosita: "alta",
    descrizione: "Apertura o allargamento di porte e finestre in muri portanti con posa di cerchiature metalliche o in c.a., secondo progetto strutturale.",
    fasi: ["Puntellamento dei solai e del muro", "Taglio del vano", "Posa della cerchiatura", "Rimozione dei puntelli a cerchiatura efficace"],
    rischi: [["Cedimento del muro o del solaio sovrastante", 2, 4], ["Caduta di materiale dall'alto", 3, 3], ["Polveri e rumore", 4, 3], ["Movimentazione di profilati pesanti", 3, 2]],
    misure: ["Lavoro solo con progetto strutturale e indicazioni del direttore dei lavori", "Prima puntellare, poi aprire", "Puntelli rimossi solo quando la cerchiatura è efficace", "Taglio ad acqua", "Sollevamento dei profilati con mezzi o in squadra"],
    dpi: ["casco", "scarpe", "guanti", "ffp3", "occhiali", "otoprotettori"],
    attrezzature: [["Puntelli metallici", "Portata verificata, integrità"]],
    formazione: ["base", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 150-156", "NTC 2018"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W035" }, pericolo: "Il muro può cedere.", regola: "Prima puntella, poi apri." },
    sostituisce: ["Cerchiature metalliche"],
  },
  {
    id: "amianto-compatto",
    nome: "Rimozione di materiali contenenti amianto",
    categoria: "demolizioni", pericolosita: "alta",
    descrizione: "Rimozione di materiali con amianto (tipicamente lastre in cemento-amianto) da parte di impresa iscritta all'Albo gestori ambientali categoria 10, con piano di lavoro presentato all'ASL.",
    fasi: ["Piano di lavoro presentato all'ASL almeno 30 giorni prima", "Confinamento e trattamento con incapsulante", "Rimozione senza rottura delle lastre", "Imballaggio, etichettatura e smaltimento"],
    rischi: [["Inalazione di fibre di amianto", 2, 4], ["Caduta dall'alto dalle coperture", 3, 4], ["Sfondamento delle lastre", 3, 4]],
    misure: ["Solo impresa iscritta all'Albo gestori ambientali cat. 10", "Piano di lavoro all'ASL (art. 256) prima di iniziare", "Lastre bagnate con incapsulante, mai rotte o tagliate", "Area confinata e accesso solo per il personale autorizzato", "Decontaminazione all'uscita dall'area", "Per le coperture: le stesse misure delle coperture fragili"],
    dpi: ["tuta_monouso", "ffp3", "guanti", "scarpe", "imbracatura", "cordino"],
    attrezzature: [["Unità di decontaminazione", "Secondo il piano di lavoro"]],
    formazione: ["amianto", "anticaduta", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 246-261", "D.M. 6/9/1994"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W016" }, pericolo: "L'amianto fa ammalare.", regola: "Entra solo se autorizzato." },
    sostituisce: ["Bonifica amianto"],
  },
  {
    id: "macerie",
    nome: "Allontanamento delle macerie",
    categoria: "demolizioni", pericolosita: "media",
    descrizione: "Calo e trasporto delle macerie dai piani con canali di scarico, gru o montacarichi, e carico sui mezzi.",
    fasi: ["Montaggio del canale di scarico", "Convogliamento delle macerie", "Carico su cassone o autocarro"],
    rischi: [["Caduta di macerie dall'alto", 3, 3], ["Polveri", 4, 2], ["Movimentazione manuale di carichi", 3, 2], ["Investimento da mezzi di carico", 2, 4]],
    misure: ["Macerie calate solo con canali chiusi o con mezzi, mai gettate (art. 153)", "Zona di arrivo del canale delimitata", "Bagnare le macerie", "Carriole e mezzi meccanici per i carichi pesanti"],
    dpi: ["casco", "scarpe", "guanti", "ffp2", "gilet"],
    attrezzature: [["Canale di scarico", "Montaggio con ancoraggi secondo il fabbricante"]],
    formazione: ["base"],
    norme: ["D.Lgs. 81/08 art. 153"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W035" }, pericolo: "Possono cadere macerie.", regola: "Usa solo il canale di scarico." },
    sostituisce: ["Smaltimento materiali di risulta"],
  },

  // ══ STRUTTURE ═══════════════════════════════════════════════════════════
  {
    id: "casseforme-armature",
    nome: "Casseforme e armature per strutture in c.a.",
    categoria: "strutture", pericolosita: "alta",
    descrizione: "Lavorazione e posa di ferri d'armatura, montaggio di casseri per fondazioni, pilastri, travi, solette e scale.",
    fasi: ["Lavorazione dei ferri al banco", "Posa delle armature", "Montaggio dei casseri", "Controllo prima del getto"],
    rischi: [["Ferite da ferri d'armatura sporgenti", 3, 3], ["Caduta dall'alto ai bordi di solette e travi", 3, 4], ["Caduta di casseri durante il sollevamento", 2, 4], ["Tagli e schiacciamenti alle mani", 3, 2], ["Movimentazione manuale di carichi", 3, 2]],
    misure: ["Cappucci di protezione sui ferri sporgenti", "Parapetti o impalcati ai bordi di lavoro in quota", "Casseri imbracati e sollevati con gru, mai a mano oltre i limiti", "Banco di lavorazione dei ferri in zona protetta", "Piegaferri e cesoie con protezioni"],
    dpi: ["casco", "scarpe", "guanti", "occhiali"],
    attrezzature: [["Piegaferri e tagliaferri", "Verifica protezioni e comandi"], ["Casseri e puntelli", "Integrità e portata"]],
    formazione: ["base", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 122, 146"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W001" }, pericolo: "I ferri sporgenti feriscono.", regola: "Metti i cappucci sui ferri." },
    sostituisce: ["Carpenteria in c.a. pilastri", "Carpenteria in c.a. travi", "Armatura casseforme fondazioni", "Scale in c.a.", "Cordoli e architravi"],
  },
  {
    id: "getto-calcestruzzo",
    nome: "Getto di calcestruzzo con autopompa o benna",
    categoria: "strutture", pericolosita: "alta",
    descrizione: "Getto di fondazioni, pilastri, travi e solai con autopompa, benna sollevata da gru o canala, con vibrazione del getto.",
    fasi: ["Posizionamento e stabilizzazione dell'autopompa", "Getto guidato dal tubo terminale", "Vibrazione", "Pulizia delle attrezzature"],
    rischi: [["Colpo di frusta del tubo terminale", 2, 4], ["Ribaltamento dell'autopompa", 1, 4], ["Contatto del braccio con linee elettriche", 1, 4], ["Caduta dai bordi del solaio durante il getto", 3, 4], ["Contatto del cemento con pelle e occhi", 3, 2], ["Vibrazioni da vibratore", 3, 2]],
    misure: ["Autopompa su terreno verificato con stabilizzatori estesi", "Nessuno sotto il braccio della pompa", "Tubo terminale guidato da una persona, mai legato al corpo", "Distanza dalle linee elettriche (Allegato IX)", "Bordi del solaio protetti", "Guanti e stivali impermeabili contro il cemento"],
    dpi: ["casco", "stivali", "guanti_chimici", "occhiali", "gilet"],
    attrezzature: [["Autopompa per calcestruzzo", "Verifiche periodiche, operatore abilitato"], ["Vibratore", "Controllo cavo e isolamento"]],
    formazione: ["pompa_cls", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 71, 73, 83", "Allegati VII, IX"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W015" }, pericolo: "Il tubo della pompa frusta.", regola: "Non stare sotto il braccio." },
    sostituisce: ["Getto solai in c.a.", "Getto fondazioni in c.a.", "Platea di fondazione"],
  },
  {
    id: "disarmo",
    nome: "Disarmo di casseforme e puntelli",
    categoria: "strutture", pericolosita: "alta",
    descrizione: "Rimozione di casseri e puntelli a maturazione avvenuta, su autorizzazione del direttore dei lavori.",
    fasi: ["Autorizzazione al disarmo", "Rimozione progressiva dei puntelli", "Rimozione dei casseri", "Pulizia e accatastamento"],
    rischi: [["Crollo della struttura disarmata troppo presto", 1, 4], ["Caduta di casseri e puntelli", 3, 3], ["Tagli e schiacciamenti", 3, 2], ["Chiodi sporgenti", 3, 2]],
    misure: ["Disarmo solo con il via libera del direttore dei lavori", "Rimuovere i puntelli in sequenza, mai tutti insieme", "Nessuno sotto la zona in disarmo", "Schiodatura e accatastamento immediati"],
    dpi: ["casco", "scarpe", "guanti"],
    attrezzature: [["Puntelli e casseri", "Integrità e pulizia prima del riutilizzo"]],
    formazione: ["base", "preposto"],
    norme: ["D.Lgs. 81/08 Titolo IV capo II"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W035" }, pericolo: "Possono cadere i puntelli.", regola: "Disarma solo se autorizzato." },
    sostituisce: [],
  },
  {
    id: "solai-posa",
    nome: "Posa di solai in laterocemento e predalles",
    categoria: "strutture", pericolosita: "alta",
    descrizione: "Posa di travetti, pignatte, lastre predalles e reti, con camminamento sul solaio in costruzione.",
    fasi: ["Puntellamento", "Posa di travetti e lastre con gru", "Posa delle pignatte", "Armature integrative e getto"],
    rischi: [["Sfondamento delle pignatte e caduta al piano sotto", 3, 4], ["Caduta dai bordi del solaio", 3, 4], ["Caduta dei carichi sollevati con la gru", 2, 4], ["Movimentazione manuale di pignatte", 3, 2]],
    misure: ["Camminare solo su tavole di ripartizione e travetti, mai sulle pignatte", "Bordi del solaio protetti con parapetti o ponteggio", "Reti o impalcato sotto il solaio dove possibile", "Nessuno sotto i carichi sollevati", "Puntelli verificati prima di caricare il solaio"],
    dpi: ["casco", "scarpe", "guanti", "imbracatura", "cordino"],
    attrezzature: [["Puntelli", "Portata e interasse da progetto"]],
    formazione: ["base", "anticaduta", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 146, 148"],
    carosello: { cartello: { tipo: "divieto", iso7010: "P024" }, pericolo: "Le pignatte si rompono.", regola: "Non camminare sulle pignatte." },
    sostituisce: ["Solai in laterocemento", "Solai collaboranti", "Rinforzo solai"],
  },
  {
    id: "prefabbricati-montaggio",
    nome: "Montaggio di strutture prefabbricate",
    categoria: "strutture", pericolosita: "alta",
    descrizione: "Montaggio di pilastri, travi, tegoli e pannelli prefabbricati con autogru, secondo il piano di montaggio del fornitore.",
    fasi: ["Verifica del piano di montaggio", "Sollevamento e posa degli elementi", "Collegamenti e sigillature", "Rimozione dei sistemi provvisori"],
    rischi: [["Caduta del carico sospeso", 2, 4], ["Caduta dall'alto durante i collegamenti", 3, 4], ["Instabilità degli elementi prima del collegamento", 2, 4], ["Schiacciamento tra elementi", 2, 4]],
    misure: ["Montaggio secondo il piano di montaggio del fornitore", "Nessuno sotto il carico o nel raggio della gru", "Elementi guidati con funi, mai con le mani sotto il carico", "Lavoro in quota da PLE o con imbracatura su punti previsti", "Elementi stabilizzati prima di sganciarli"],
    dpi: ["casco", "scarpe", "guanti", "imbracatura", "cordino", "gilet"],
    attrezzature: [["Autogru", "Verifiche periodiche, operatore abilitato"], ["Brache e bilancini", "Marcatura e controllo prima dell'uso"]],
    formazione: ["anticaduta", "preposto", "ple"],
    norme: ["D.Lgs. 81/08 artt. 71, 73", "Titolo IV capo II"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W015" }, pericolo: "Il pezzo appeso può cadere.", regola: "Non stare sotto il carico." },
    sostituisce: ["Strutture prefabbricate"],
  },
  {
    id: "acciaio-montaggio",
    nome: "Montaggio di strutture in acciaio e legno",
    categoria: "strutture", pericolosita: "alta",
    descrizione: "Montaggio di colonne, travi e coperture in carpenteria metallica o legno lamellare, con bullonatura in quota.",
    fasi: ["Sollevamento degli elementi", "Posa e bullonatura provvisoria", "Serraggio e controventature", "Posa di coperture e solai"],
    rischi: [["Caduta dall'alto dalle travi", 3, 4], ["Caduta di elementi sollevati", 2, 4], ["Caduta di bulloni e attrezzi", 3, 3], ["Schiacciamento delle mani", 3, 2]],
    misure: ["Lavoro in quota da PLE o con imbracatura su linee vita previste", "Nessuno sotto le zone di montaggio", "Attrezzi legati o in borse chiuse", "Elementi controventati prima dello sgancio"],
    dpi: ["casco", "scarpe", "guanti", "imbracatura", "cordino", "retrattile"],
    attrezzature: [["Autogru o gru a torre", "Verifiche periodiche"], ["Avvitatori", "Controllo prima dell'uso"]],
    formazione: ["anticaduta", "ple", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 111, 115"],
    carosello: { cartello: { tipo: "obbligo", iso7010: "M018" }, pericolo: "Sulle travi si cade.", regola: "Aggancia sempre l'imbracatura." },
    sostituisce: ["Strutture in acciaio", "Strutture in legno lamellare", "Scale metalliche"],
  },
  {
    id: "puntellature",
    nome: "Puntellature e opere di sostegno provvisorie",
    categoria: "strutture", pericolosita: "alta",
    descrizione: "Puntellamento di solai, murature, volte e fronti di scavo durante consolidamenti, demolizioni e ristrutturazioni.",
    fasi: ["Progetto o schema della puntellatura", "Posa dei puntelli", "Controlli periodici", "Rimozione su autorizzazione"],
    rischi: [["Crollo per puntelli insufficienti o rimossi", 2, 4], ["Caduta di puntelli", 3, 2], ["Schiacciamento", 2, 3]],
    misure: ["Puntellatura secondo schema del tecnico", "Puntelli su appoggi solidi e ripartiti", "Mai rimuovere un puntello senza autorizzazione", "Controllo dopo urti, vibrazioni o lavori vicini"],
    dpi: ["casco", "scarpe", "guanti"],
    attrezzature: [["Puntelli metallici", "Portata dichiarata, integrità"]],
    formazione: ["base", "preposto"],
    norme: ["D.Lgs. 81/08 Titolo IV capo II"],
    carosello: { cartello: { tipo: "divieto", iso7010: "P001" }, pericolo: "Senza puntelli crolla tutto.", regola: "Non togliere i puntelli." },
    sostituisce: ["Consolidamento volte", "Consolidamento murature", "Cuci-scuci murature"],
  },

  // ══ SOLLEVAMENTI E MEZZI ════════════════════════════════════════════════
  {
    id: "gru-torre-uso",
    nome: "Movimentazione di carichi con gru a torre",
    categoria: "sollevamenti", pericolosita: "alta",
    descrizione: "Sollevamento e trasporto di materiali con gru a torre, con imbracatura dei carichi e guida da terra.",
    fasi: ["Controllo giornaliero della gru", "Imbracatura del carico", "Sollevamento e trasporto", "Deposito e sgancio"],
    rischi: [["Caduta del carico sospeso", 2, 4], ["Urto del carico contro persone o strutture", 2, 4], ["Interferenza con altre gru o linee elettriche", 1, 4], ["Ribaltamento per vento o sovraccarico", 1, 4]],
    misure: ["Gruista abilitato, segnalatore a terra con segnali concordati", "Nessuno sotto il carico sospeso", "Brache e ganci con marcatura e portata adeguata", "Carichi sfusi in ceste o contenitori chiusi", "Fermare la gru oltre la velocità del vento indicata dal fabbricante", "Rispetto della tabella dei carichi"],
    dpi: ["casco", "scarpe", "guanti", "gilet"],
    attrezzature: [["Gru a torre", "Verifiche periodiche (Allegato VII), controllo giornaliero"], ["Brache, catene, ganci", "Controllo trimestrale delle funi (Allegato VI)"]],
    formazione: ["gru_torre", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 71, 73", "Allegati VI, VII"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W015" }, pericolo: "Il carico può cadere.", regola: "Non stare sotto il carico." },
    sostituisce: [],
  },
  {
    id: "gru-torre-montaggio",
    nome: "Montaggio e smontaggio della gru a torre",
    categoria: "sollevamenti", pericolosita: "alta",
    descrizione: "Installazione, montaggio e smontaggio della gru a torre secondo il manuale del fabbricante, da parte di montatori specializzati.",
    fasi: ["Verifica del basamento", "Montaggio con autogru", "Collaudo e verifiche", "Smontaggio a fine lavori"],
    rischi: [["Caduta dall'alto dalla torre e dal braccio", 2, 4], ["Caduta di elementi in montaggio", 2, 4], ["Crollo per basamento non adeguato", 1, 4]],
    misure: ["Montaggio solo da ditta specializzata secondo il manuale", "Basamento da calcolo del tecnico", "Area di montaggio interdetta", "Imbracatura sempre agganciata sulla struttura", "Messa a terra e verifica prima della messa in servizio"],
    dpi: ["casco", "scarpe", "guanti", "imbracatura", "cordino"],
    attrezzature: [["Gru a torre", "Denuncia di installazione e prima verifica INAIL"]],
    formazione: ["montatori_gru", "anticaduta"],
    norme: ["D.Lgs. 81/08 art. 71 c.11", "Allegato VII"],
    carosello: { cartello: { tipo: "divieto", iso7010: "P004" }, pericolo: "Si sta montando la gru.", regola: "Stai fuori dall'area chiusa." },
    sostituisce: ["Installazione gru a torre"],
  },
  {
    id: "autogru",
    nome: "Sollevamenti con autogru",
    categoria: "sollevamenti", pericolosita: "alta",
    descrizione: "Sollevamenti con gru su autocarro o autogru, con stabilizzazione sul terreno e manovre in spazi ristretti o su strada.",
    fasi: ["Verifica del terreno e degli spazi", "Stabilizzazione", "Sollevamento guidato", "Ripiegamento"],
    rischi: [["Ribaltamento per terreno cedevole", 2, 4], ["Caduta o oscillazione del carico", 2, 4], ["Contatto con linee elettriche aeree", 1, 4], ["Schiacciamento tra mezzo e ostacoli", 2, 4]],
    misure: ["Operatore abilitato e segnalatore a terra", "Stabilizzatori estesi su piastre di ripartizione", "Area di manovra delimitata", "Distanze dalle linee elettriche (Allegato IX)", "Funi guida per controllare il carico"],
    dpi: ["casco", "scarpe", "guanti", "gilet"],
    attrezzature: [["Autogru", "Verifiche periodiche (Allegato VII)"]],
    formazione: ["autogru", "preposto"],
    norme: ["D.Lgs. 81/08 artt. 71, 73, 83"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W015" }, pericolo: "Il carico può oscillare.", regola: "Stai lontano dalla gru." },
    sostituisce: [],
  },
  {
    id: "sollevatore-telescopico",
    nome: "Uso di sollevatore telescopico e carrello elevatore",
    categoria: "sollevamenti", pericolosita: "alta",
    descrizione: "Movimentazione di bancali e materiali con sollevatore telescopico o carrello elevatore in cantiere.",
    fasi: ["Controllo del mezzo", "Presa del carico", "Trasporto e sollevamento", "Deposito"],
    rischi: [["Investimento di persone", 3, 4], ["Ribaltamento del mezzo", 2, 4], ["Caduta del carico", 2, 3]],
    misure: ["Solo operatori abilitati", "Percorsi separati per mezzi e pedoni", "Carico basso durante gli spostamenti", "Rispetto del diagramma di carico", "Mai trasportare persone sulle forche"],
    dpi: ["casco", "scarpe", "gilet"],
    attrezzature: [["Sollevatore telescopico", "Verifiche periodiche se previste, controllo giornaliero"]],
    formazione: ["sollevatore"],
    norme: ["D.Lgs. 81/08 artt. 71, 73"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W014" }, pericolo: "Il mezzo non ti vede.", regola: "Fatti vedere dal manovratore." },
    sostituisce: [],
  },
  {
    id: "mezzi-movimento-terra",
    nome: "Uso di escavatori, pale e terne",
    categoria: "sollevamenti", pericolosita: "alta",
    descrizione: "Movimento terra, rinterri, riporti e livellamenti con macchine operatrici, con persone a terra nelle vicinanze.",
    fasi: ["Controllo del mezzo", "Delimitazione dell'area di lavoro", "Lavorazione", "Parcheggio sicuro a fine turno"],
    rischi: [["Investimento o schiacciamento di persone a terra", 3, 4], ["Ribaltamento del mezzo su pendii o bordi", 2, 4], ["Rumore e vibrazioni", 3, 2], ["Polveri", 3, 2]],
    misure: ["Solo operatori abilitati", "Nessuno nel raggio d'azione della macchina", "Segnalatore a terra in caso di scarsa visibilità", "Avvisatore di retromarcia funzionante", "Mai usare la benna per sollevare persone", "Bagnare le piste contro la polvere"],
    dpi: ["casco", "scarpe", "gilet", "otoprotettori"],
    attrezzature: [["Escavatore, pala, terna", "Manutenzione secondo il libretto, controllo giornaliero"]],
    formazione: ["mmt"],
    norme: ["D.Lgs. 81/08 artt. 71, 73"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W014" }, pericolo: "L'escavatore non ti vede.", regola: "Stai lontano dalla macchina." },
    sostituisce: ["Rinterri e riporti", "Consolidamento terreno", "Sradicamento alberature", "Preparazione terreno"],
  },
  {
    id: "autocarri-carico",
    nome: "Carico, scarico e circolazione di autocarri",
    categoria: "sollevamenti", pericolosita: "media",
    descrizione: "Ingresso, manovra, carico e scarico di autocarri e ribaltabili, compresa la gru su autocarro per lo scarico materiali.",
    fasi: ["Ingresso guidato in cantiere", "Manovra e posizionamento", "Carico o scarico", "Uscita"],
    rischi: [["Investimento in retromarcia", 3, 4], ["Ribaltamento del cassone su terreno in pendenza", 1, 4], ["Caduta di materiali durante lo scarico", 2, 3]],
    misure: ["Manovre in retromarcia guidate da un segnalatore", "Nessuno dietro al mezzo in manovra", "Ribaltamento del cassone solo su terreno piano", "Zone di carico e scarico definite e segnalate"],
    dpi: ["casco", "scarpe", "gilet", "guanti"],
    attrezzature: [["Gru su autocarro", "Verifiche periodiche, operatore abilitato"]],
    formazione: ["base"],
    norme: ["D.Lgs. 81/08 art. 108", "Allegato XVIII"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W014" }, pericolo: "Il camion fa retromarcia.", regola: "Non stare dietro al camion." },
    sostituisce: ["Zone carico/scarico", "Viabilità interna"],
  },

  // ══ LAVORI A CALDO E PRODOTTI CHIMICI ═══════════════════════════════════
  {
    id: "guaina-fiamma",
    nome: "Impermeabilizzazione con guaina a fiamma",
    categoria: "caldo_chimico", pericolosita: "alta",
    descrizione: "Posa di membrane bituminose saldate a fiamma con cannello a gas su coperture, terrazzi, fondazioni.",
    fasi: ["Preparazione del piano e primer", "Posizionamento delle bombole", "Saldatura a fiamma dei teli", "Controllo finale anti-focolaio"],
    rischi: [["Incendio di materiali vicini o sottostanti", 2, 4], ["Ustioni", 3, 3], ["Esplosione o perdita delle bombole di gas", 1, 4], ["Caduta dall'alto in copertura", 3, 4], ["Fumi di bitume", 3, 2]],
    misure: ["Estintore sempre a portata di mano", "Bombole in piedi, lontane dalla fiamma, mai in luoghi chiusi", "Tubi e riduttori controllati prima dell'uso", "Nessun materiale infiammabile vicino (isolanti, legno)", "Controllo dell'area un'ora dopo la fine contro focolai nascosti", "Protezioni anticaduta come per i lavori su coperture"],
    dpi: ["scarpe", "guanti_calore", "abiti_calore", "occhiali", "imbracatura", "cordino"],
    attrezzature: [["Cannello e bombole GPL", "Controllo tubi, riduttore e valvole prima dell'uso"], ["Estintore", "Revisione semestrale"]],
    formazione: ["base", "antincendio", "anticaduta"],
    norme: ["D.Lgs. 81/08 art. 46", "D.M. 2/9/2021"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W021" }, pericolo: "La fiamma dà fuoco.", regola: "Tieni l'estintore vicino." },
    sostituisce: ["Guaine bituminose"],
  },
  {
    id: "saldatura-taglio",
    nome: "Saldatura e taglio termico dei metalli",
    categoria: "caldo_chimico", pericolosita: "alta",
    descrizione: "Saldatura ad arco o a filo, taglio con cannello ossiacetilenico o plasma, molatura di elementi metallici.",
    fasi: ["Allontanamento dei materiali infiammabili", "Preparazione dei pezzi", "Saldatura o taglio", "Controllo anti-focolaio"],
    rischi: [["Incendio da scintille e scorie", 2, 4], ["Radiazioni ottiche e ustioni", 3, 3], ["Fumi di saldatura", 3, 3], ["Elettrocuzione", 2, 4], ["Proiezione di schegge da mola", 3, 3]],
    misure: ["Materiali infiammabili rimossi o coperti in un raggio adeguato", "Estintore vicino e controllo a fine lavoro", "Aspirazione dei fumi o lavoro all'aperto", "Schermi per proteggere chi è vicino", "Saldatrice e cavi integri, pinza di massa vicina al pezzo", "Bombole ancorate e con valvole antiritorno di fiamma"],
    dpi: ["maschera_saldatura", "abiti_saldatura", "guanti_calore", "scarpe", "ffp2"],
    attrezzature: [["Saldatrice", "Integrità di cavi e pinze"], ["Bombole ossigeno e acetilene", "Valvole antiritorno, ancoraggio"]],
    formazione: ["base", "antincendio"],
    norme: ["D.Lgs. 81/08 art. 46", "Titolo VIII capo V (radiazioni ottiche)", "Titolo IX capo II (fumi di saldatura)"],
    carosello: { cartello: { tipo: "obbligo", iso7010: "M019" }, pericolo: "Le scintille bruciano.", regola: "Usa la maschera da saldatore." },
    sostituisce: ["Opere in ferro", "Opere da fabbro", "Rimozione elementi in ferro"],
  },
  {
    id: "resine-solventi",
    nome: "Uso di resine, solventi e prodotti chimici",
    categoria: "caldo_chimico", pericolosita: "media",
    descrizione: "Posa di pavimenti in resina, iniezioni, primer, adesivi, impregnanti, sverniciatori e altri prodotti con schede di sicurezza.",
    fasi: ["Lettura della scheda di sicurezza", "Ventilazione dell'ambiente", "Miscelazione e applicazione", "Smaltimento dei contenitori"],
    rischi: [["Contatto con pelle e occhi", 3, 3], ["Inalazione di vapori", 3, 3], ["Incendio di vapori infiammabili", 2, 4], ["Sensibilizzazione allergica (resine epossidiche)", 3, 3]],
    misure: ["Scheda di sicurezza disponibile e letta prima dell'uso", "Ambienti ventilati, in spazi chiusi ventilazione forzata", "Nessuna fiamma o scintilla vicino a prodotti infiammabili", "Contenitori chiusi ed etichettati", "Lavaggio delle mani prima di mangiare"],
    dpi: ["guanti_chimici", "occhiali", "semimaschera_a", "tuta_monouso"],
    attrezzature: [["Miscelatore", "Controllo cavo e protezioni"]],
    formazione: ["base"],
    norme: ["D.Lgs. 81/08 Titolo IX capo I", "Regolamento CLP"],
    carosello: { cartello: { tipo: "obbligo", iso7010: "M009" }, pericolo: "I prodotti bruciano la pelle.", regola: "Metti guanti e occhiali." },
    sostituisce: ["Pavimento in resina", "Iniezioni di resina", "Barriera chimica", "Rinforzi strutturali FRP", "Impermeabilizzazione liquida"],
  },
  {
    id: "asfalto-caldo",
    nome: "Stesa di conglomerato bituminoso a caldo",
    categoria: "caldo_chimico", pericolosita: "alta",
    descrizione: "Stesa e rullatura di asfalto a caldo con vibrofinitrice e rulli, spesso su strada aperta al traffico.",
    fasi: ["Segnaletica e delimitazione", "Spruzzatura dell'emulsione", "Stesa con vibrofinitrice", "Rullatura"],
    rischi: [["Investimento da veicoli in transito o mezzi d'opera", 3, 4], ["Ustioni da materiale a 160 °C", 3, 3], ["Fumi di bitume", 3, 2], ["Caldo e sole", 3, 3]],
    misure: ["Segnaletica secondo gli schemi del D.M. 10/7/2002", "Nessuno dietro i rulli in retromarcia", "Non toccare il materiale caldo, stivali adatti", "Acqua, pause e turni nelle ore calde"],
    dpi: ["gilet", "scarpe", "guanti_calore", "casco"],
    attrezzature: [["Vibrofinitrice e rulli", "Avvisatori acustici e luminosi funzionanti"]],
    formazione: ["segnaletica", "mmt"],
    norme: ["D.I. 22/01/2019", "D.M. 10/7/2002"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W017" }, pericolo: "L'asfalto scotta.", regola: "Non toccare il materiale caldo." },
    sostituisce: ["Asfalto"],
  },

  // ══ RISCHIO ELETTRICO ═══════════════════════════════════════════════════
  {
    id: "impianto-cantiere",
    nome: "Impianto elettrico di cantiere",
    categoria: "elettrico", pericolosita: "alta",
    descrizione: "Installazione, modifica e uso dell'impianto elettrico di cantiere: quadri ASC, linee, prese, messa a terra.",
    fasi: ["Installazione da impresa abilitata", "Dichiarazione di conformità", "Uso quotidiano di quadri e prolunghe", "Verifiche periodiche"],
    rischi: [["Elettrocuzione da cavi danneggiati o quadri aperti", 2, 4], ["Incendio da sovraccarico", 1, 4], ["Inciampo sui cavi", 3, 2]],
    misure: ["Impianto realizzato da impresa abilitata con dichiarazione di conformità (D.M. 37/2008)", "Quadri ASC chiusi, prese con interruttore differenziale", "Cavi adatti alla posa mobile, sollevati o protetti nei passaggi", "Nessuna riparazione di fortuna: si sostituisce il cavo", "Verifica dell'impianto di terra (D.P.R. 462/2001)"],
    dpi: ["scarpe", "guanti"],
    attrezzature: [["Quadri elettrici ASC", "Conformi CEI EN 61439-4"], ["Impianto di terra", "Denuncia e verifiche periodiche (D.P.R. 462/2001)"]],
    formazione: ["base"],
    norme: ["D.Lgs. 81/08 artt. 80-86", "D.M. 37/2008", "D.P.R. 462/2001"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W012" }, pericolo: "La corrente uccide.", regola: "Non toccare quadri e cavi rotti." },
    sostituisce: ["Impianto elettrico di cantiere", "Cabina elettrica temporanea", "Illuminazione cantiere"],
  },
  {
    id: "impianti-elettrici",
    nome: "Lavori su impianti elettrici",
    categoria: "elettrico", pericolosita: "alta",
    descrizione: "Realizzazione e modifica di impianti elettrici dell'edificio: quadri, linee, prese, illuminazione, impianto di terra.",
    fasi: ["Sezionamento e messa in sicurezza", "Verifica di assenza di tensione", "Esecuzione dei lavori", "Collaudo e rimessa in tensione"],
    rischi: [["Elettrocuzione per lavoro su parti in tensione", 2, 4], ["Arco elettrico", 1, 4], ["Caduta da scale o trabattelli", 2, 3]],
    misure: ["Lavori fuori tensione: sezionare, bloccare con lucchetto, segnalare, verificare", "Solo personale PES/PAV secondo CEI 11-27", "Attrezzi isolati", "Rimessa in tensione solo da chi ha messo il blocco"],
    dpi: ["guanti_dielettrici", "casco_dielettrico", "visiera", "scarpe"],
    attrezzature: [["Rilevatore di tensione", "Prova di funzionamento prima dell'uso"], ["Attrezzi isolati 1000 V", "Integrità dell'isolamento"]],
    formazione: ["pes_pav"],
    norme: ["D.Lgs. 81/08 art. 82", "CEI 11-27", "CEI EN 50110"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W012" }, pericolo: "La corrente uccide.", regola: "Lavora solo a corrente staccata." },
    sostituisce: ["Quadro elettrico generale", "Impianto elettrico civile", "Impianto elettrico industriale", "Impianto di terra", "Impianto parafulmine"],
  },
  {
    id: "linee-aeree",
    nome: "Lavori vicino a linee elettriche aeree",
    categoria: "elettrico", pericolosita: "alta",
    descrizione: "Lavori con gru, autopompe, PLE, ponteggi o mezzi in prossimità di linee elettriche aeree.",
    fasi: ["Individuazione delle linee e della tensione", "Accordo con l'ente gestore se serve", "Delimitazione della zona", "Lavoro sorvegliato"],
    rischi: [["Elettrocuzione per contatto o scarica dalla linea", 2, 4]],
    misure: ["Rispetto delle distanze minime dell'Allegato IX (3 m fino a 1 kV, 3,5 m fino a 30 kV, 5 m fino a 132 kV, 7 m oltre)", "Se non è possibile: richiesta di messa fuori tensione all'ente gestore", "Sbarramenti e segnalazioni per i mezzi", "Persona a terra che sorveglia la distanza durante le manovre"],
    dpi: ["casco", "scarpe", "gilet"],
    attrezzature: [["Gru, autopompe, PLE", "Limitatori di movimento dove disponibili"]],
    formazione: ["base", "preposto"],
    norme: ["D.Lgs. 81/08 art. 83", "Allegato IX"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W012" }, pericolo: "I fili sopra di te uccidono.", regola: "Tieni i mezzi lontani dai fili." },
    sostituisce: [],
  },

  // ══ ALTRE LAVORAZIONI A RISCHIO ═════════════════════════════════════════
  {
    id: "spazi-confinati",
    nome: "Lavori in spazi confinati o sospetti di inquinamento",
    categoria: "altri", pericolosita: "alta",
    descrizione: "Lavori in pozzi, cisterne, vasche, fosse biologiche, cunicoli, camere di ispezione, serbatoi e simili.",
    fasi: ["Procedura scritta e permesso di lavoro", "Misura dell'atmosfera", "Ingresso con sorvegliante esterno", "Recupero ed emergenza"],
    rischi: [["Asfissia per mancanza di ossigeno", 2, 4], ["Intossicazione da gas (idrogeno solforato, monossido)", 2, 4], ["Incendio o esplosione", 1, 4], ["Difficoltà di soccorso", 3, 4]],
    misure: ["Solo imprese qualificate secondo il D.P.R. 177/2011", "Procedura scritta e permesso di lavoro", "Misura di ossigeno e gas prima e durante il lavoro", "Ventilazione forzata", "Sorvegliante sempre all'esterno, mai entrare a soccorrere senza protezioni", "Sistema di recupero (treppiede e imbracatura) pronto"],
    dpi: ["imbracatura", "autorespiratore", "casco", "scarpe", "guanti"],
    attrezzature: [["Rilevatore multigas", "Taratura periodica"], ["Treppiede e verricello di recupero", "Conforme UNI EN 795 e UNI EN 1496"]],
    formazione: ["spazi_confinati", "preposto", "primo_soccorso"],
    norme: ["D.P.R. 177/2011", "D.Lgs. 81/08 artt. 66, 121"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W041" }, pericolo: "Dentro manca l'aria.", regola: "Non entrare senza permesso." },
    sostituisce: ["Pozzetti e caditoie"],
  },
  {
    id: "lavori-stradali",
    nome: "Lavori su strada aperta al traffico",
    categoria: "altri", pericolosita: "alta",
    descrizione: "Cantieri stradali e lavori su marciapiedi, sottoservizi e segnaletica con traffico veicolare in presenza.",
    fasi: ["Posa della segnaletica nell'ordine previsto", "Lavorazione dentro l'area delimitata", "Rimozione della segnaletica in ordine inverso"],
    rischi: [["Investimento da veicoli in transito", 3, 4], ["Investimento da mezzi d'opera", 2, 4], ["Scarsa visibilità di notte o con nebbia", 2, 4]],
    misure: ["Segnaletica secondo gli schemi del D.M. 10/7/2002", "Posa e rimozione della segnaletica solo da personale formato", "Indumenti ad alta visibilità sempre indossati", "Mai uscire dall'area delimitata", "Movieri o semafori dove richiesto"],
    dpi: ["gilet", "casco", "scarpe"],
    attrezzature: [["Segnaletica temporanea", "Integrità e visibilità, luci funzionanti"]],
    formazione: ["segnaletica"],
    norme: ["D.I. 22/01/2019", "D.M. 10/7/2002", "Codice della strada art. 21"],
    carosello: { cartello: { tipo: "obbligo", iso7010: "M015" }, pericolo: "Le auto passano vicino.", regola: "Metti sempre il gilet." },
    sostituisce: [],
  },
  {
    id: "murature-movimentazione",
    nome: "Murature e movimentazione di blocchi pesanti",
    categoria: "altri", pericolosita: "media",
    descrizione: "Costruzione di murature in laterizio, blocchi e pietra, con movimentazione manuale e lavoro da ponti su cavalletti o ponteggio.",
    fasi: ["Approvvigionamento dei materiali al piano", "Preparazione della malta", "Posa dei blocchi", "Pulizia"],
    rischi: [["Lesioni alla schiena per movimentazione manuale", 4, 3], ["Caduta da ponti su cavalletti", 2, 3], ["Contatto con malta e cemento", 3, 2], ["Tagli da taglio laterizi", 2, 3]],
    misure: ["Materiali portati al piano con mezzi, non a mano", "Blocchi oltre 25 kg sollevati in due o con mezzi (Allegato XXXIII)", "Ponti su cavalletti solo fino a 2 m e con tavole fissate", "Taglio laterizi con sega ad acqua"],
    dpi: ["casco", "scarpe", "guanti", "occhiali"],
    attrezzature: [["Betoniera", "Protezioni degli organi in movimento, interruttore di emergenza"], ["Ponti su cavalletti", "Tavole integre e fissate"]],
    formazione: ["base"],
    norme: ["D.Lgs. 81/08 Titolo VI, Allegato XXXIII", "art. 139"],
    carosello: { cartello: { tipo: "pericolo", iso7010: "W001" }, pericolo: "I pesi rovinano la schiena.", regola: "Solleva in due i pesi grossi." },
    sostituisce: ["Murature in laterizio", "Murature in blocchi", "Muri di tamponamento", "Murature faccia vista", "Murature portanti", "Muri di contenimento"],
  },
  {
    id: "vetrate-grandi-lastre",
    nome: "Posa di vetrate e grandi lastre",
    categoria: "altri", pericolosita: "media",
    descrizione: "Movimentazione e posa di vetrate, serramenti di grandi dimensioni e lastre di pietra o gres di grande formato.",
    fasi: ["Trasporto al piano", "Sollevamento con ventose o mezzi", "Posa e fissaggio"],
    rischi: [["Rottura della lastra con tagli gravi", 2, 4], ["Caduta della lastra durante il sollevamento", 2, 4], ["Movimentazione di carichi ingombranti", 3, 3], ["Caduta dall'alto durante la posa in facciata", 2, 4]],
    misure: ["Sollevamento con ventose o sollevatori, mai a mano oltre i limiti", "Lastre trasportate in verticale su carrelli dedicati", "Area di posa libera da persone non coinvolte", "Posa in facciata da ponteggio o PLE"],
    dpi: ["guanti", "scarpe", "occhiali", "casco"],
    attrezzature: [["Ventose e sollevatori per lastre", "Verifica della tenuta prima di ogni sollevamento"]],
    formazione: ["base"],
    norme: ["D.Lgs. 81/08 Titolo VI"],
    carosello: { cartello: { tipo: "obbligo", iso7010: "M009" }, pericolo: "Il vetro rotto taglia.", regola: "Solleva con le ventose." },
    sostituisce: ["Vetrate fisse"],
  },
];

// Ogni scheda nasce "bozza": diventa "verificata" solo con il nome di chi
// l'ha riletta (RSPP/CSE) e la data.
for (const s of SCHEDE) {
  if (!s.revisione) s.revisione = { stato: "bozza", da: null, data: null };
}
deepFreeze(SCHEDE);
deepFreeze(DPI);
deepFreeze(FORMAZIONE);
deepFreeze(CATEGORIE);

function deepFreeze(o) {
  if (o && typeof o === "object" && !Object.isFrozen(o)) {
    Object.freeze(o);
    for (const v of Object.values(o)) deepFreeze(v);
  }
  return o;
}

// ── Accessori ────────────────────────────────────────────────────────────────
const BY_ID = new Map(SCHEDE.map(s => [s.id, s]));
const BY_VOCE_VECCHIA = new Map();
for (const s of SCHEDE) for (const v of s.sostituisce) BY_VOCE_VECCHIA.set(v, s.id);

function livello(r) {
  if (r >= 12) return "Molto alto";
  if (r >= 8) return "Alto";
  if (r >= 4) return "Medio";
  return "Basso";
}

/** Rischi espansi con R = P×D e livello. */
function rischiValutati(scheda) {
  return scheda.rischi.map(([rischio, p, d]) => ({ rischio, p, d, r: p * d, livello: livello(p * d) }));
}

function getScheda(id) {
  return BY_ID.get(id) || null;
}

/** Voce del vecchio catalogo → id della scheda che la sostituisce (o null). */
function schedaPerVoceVecchia(voce) {
  return BY_VOCE_VECCHIA.get(voce) || null;
}

module.exports = {
  DPI, FORMAZIONE, CATEGORIE, TIPI_CARTELLO, SCHEDE,
  getScheda, schedaPerVoceVecchia, rischiValutati, livello,
};
