'use strict';
/**
 * lib/lavorazioniSchedeExtra.js — F-299 (AUDIT.md del frontend). Lavorazioni
 * che il primo coordinatore vero non trovava ("mancano molte lavorazioni e
 * fasi", confronto con i software che usano i CSE). Stesso formato delle
 * schede di lib/lavorazioniSchede.js, che le unisce alle sue: rischi
 * [descrizione, P, D], attrezzature [nome, verifica], carosello con due frasi
 * brevi. Testi scritti da Palladia, da rivedere come le altre (stato "bozza").
 */
const B = (s) => ({ sostituisce: [], revisione: { stato: 'bozza', da: null, data: null }, ...s });

const SCHEDE_EXTRA = [
  // ══ LAVORI IN QUOTA ══
  B({
    id: 'linee-vita-permanenti',
    nome: 'Installazione di linee vita e ancoraggi permanenti',
    categoria: 'quota', pericolosita: 'alta',
    descrizione: 'Posa in copertura di dispositivi di ancoraggio permanenti (UNI EN 795, UNI 11578): ganci, punti fissi e linee flessibili, con fissaggio alla struttura e collaudo.',
    fasi: ['Accesso alla copertura con protezioni provvisorie', 'Foratura e fissaggio dei supporti alla struttura', 'Tesatura della fune e montaggio degli accessori', 'Collaudo, cartellonistica e fascicolo tecnico'],
    rischi: [['Caduta dal bordo prima che la linea sia collaudata', 3, 4], ['Scivolamento su falde inclinate', 3, 3], ['Caduta di attrezzi verso il basso', 2, 3], ['Polveri e schegge durante la foratura', 3, 2]],
    misure: ['Fino al collaudo si lavora protetti da parapetti provvisori o ponteggio, mai agganciati alla linea in posa', 'Fissaggi solo sugli elementi strutturali indicati nel progetto della linea', 'Area sottostante delimitata', 'Collaudo e dichiarazione dell\'installatore prima dell\'uso'],
    dpi: ['casco', 'scarpe', 'guanti', 'imbracatura', 'cordino', 'occhiali'],
    attrezzature: [['Trapano e avvitatore a batteria', 'Integrità e cordino anticaduta degli attrezzi'], ['Dinamometro per la tesatura', 'Taratura']],
    formazione: ['base', 'anticaduta', 'preposto'],
    norme: ['D.Lgs. 81/08 artt. 111, 115', 'UNI EN 795', 'UNI 11578'],
    carosello: { cartello: { tipo: 'obbligo', iso7010: 'M018' }, pericolo: 'La linea nuova non tiene ancora.', regola: 'Lavora dietro al parapetto.' },
  }),
  // ══ SCAVI ══
  B({
    id: 'rinterri-compattazione',
    nome: 'Rinterri, riempimenti e compattazione',
    categoria: 'scavi', pericolosita: 'media',
    descrizione: 'Rinterro di scavi e trincee, riempimenti con misto granulare, stesa a strati e compattazione con piastre vibranti o rulli.',
    fasi: ['Verifica del fondo e delle opere da ricoprire', 'Scarico e stesa del materiale a strati', 'Compattazione con piastra o rullo', 'Prove di carico se richieste'],
    rischi: [['Investimento da mezzi in retromarcia', 2, 4], ['Vibrazioni mano-braccio dalla piastra vibrante', 3, 2], ['Rumore', 3, 2], ['Caduta nello scavo non ancora riempito', 2, 3], ['Polveri', 3, 2]],
    misure: ['Manovre dei mezzi assistite da un operatore a terra', 'Nessuno nel raggio d\'azione dei mezzi', 'Rotazione degli addetti alla piastra vibrante', 'Bordi dello scavo segnalati fino al riempimento', 'Bagnare il materiale per ridurre la polvere'],
    dpi: ['casco', 'scarpe', 'guanti', 'otoprotettori', 'gilet'],
    attrezzature: [['Piastra vibrante o rullo compattatore', 'Manutenzione e valutazione vibrazioni'], ['Escavatore o pala', 'Verifiche periodiche, operatore abilitato']],
    formazione: ['base', 'mmt'],
    norme: ['D.Lgs. 81/08 Titolo IV capo II', 'Titolo VIII capo III'],
    carosello: { cartello: { tipo: 'pericolo', iso7010: 'W001' }, pericolo: 'Il mezzo in retromarcia investe.', regola: 'Stai lontano dai mezzi.' },
  }),
  B({
    id: 'fognature-tubazioni',
    nome: 'Posa di tubazioni e pozzetti in trincea (fognature, acquedotti)',
    categoria: 'scavi', pericolosita: 'alta',
    descrizione: 'Posa di condotte, pozzetti e camerette per fognature, acquedotti e drenaggi in trincea armata, con allacciamenti a reti esistenti.',
    fasi: ['Scavo della trincea e armatura delle pareti', 'Livellamento del letto di posa', 'Calo e giunzione dei tubi e dei pozzetti', 'Prova di tenuta e rinfianco'],
    rischi: [['Seppellimento per franamento delle pareti', 2, 4], ['Carichi sospesi durante il calo dei tubi', 3, 3], ['Gas e mancanza di ossigeno in pozzetti e reti esistenti', 2, 4], ['Contatto con liquami e rischio biologico', 3, 3], ['Investimento da mezzi', 2, 4]],
    misure: ['Pareti armate o a scarpa oltre 1,5 m di profondità', 'Nessuno nella trincea durante il calo dei tubi', 'Allacciamenti a reti esistenti come spazio confinato: misura dei gas, ventilazione e addetto all\'esterno', 'Guanti e lavaggio delle mani per il rischio biologico', 'Bordi della trincea delimitati e materiali a distanza dal ciglio'],
    dpi: ['casco', 'stivali', 'guanti_chimici', 'gilet', 'ffp2'],
    attrezzature: [['Blindaggi metallici per trincee', 'Montaggio secondo il fabbricante'], ['Escavatore con gancio di sollevamento', 'Verifiche periodiche, operatore abilitato'], ['Rilevatore multigas', 'Taratura']],
    formazione: ['base', 'mmt', 'spazi_confinati', 'preposto'],
    norme: ['D.Lgs. 81/08 artt. 118-121', 'D.P.R. 177/2011', 'Titolo X'],
    carosello: { cartello: { tipo: 'divieto', iso7010: 'P004' }, pericolo: 'Il tubo appeso può cadere.', regola: 'Esci dalla trincea al calo.' },
  }),
  // ══ STRUTTURE ══
  B({
    id: 'ferro-lavorazione',
    nome: 'Lavorazione e posa delle armature in acciaio',
    categoria: 'strutture', pericolosita: 'media',
    descrizione: 'Taglio, piegatura e legatura delle barre d\'armatura al banco o in opera, posa di gabbie e reti elettrosaldate.',
    fasi: ['Scarico e stoccaggio delle barre', 'Taglio e piegatura al banco', 'Legatura e posa delle gabbie', 'Protezione dei ferri sporgenti'],
    rischi: [['Tagli e punture dai ferri sporgenti', 4, 2], ['Schiacciamento durante la movimentazione delle gabbie', 2, 3], ['Movimentazione manuale di carichi', 3, 2], ['Contatto con parti in movimento della piegaferri', 2, 3]],
    misure: ['Cappucci di protezione su tutti i ferri sporgenti', 'Gabbie pesanti movimentate con gru e imbracature verificate', 'Piegaferri e cesoie con protezioni e comando a uomo presente', 'Banco di lavorazione in zona delimitata, fuori dai percorsi'],
    dpi: ['casco', 'scarpe', 'guanti', 'occhiali'],
    attrezzature: [['Piegaferri e cesoia', 'Protezioni montate, manutenzione'], ['Funi e catene di imbracatura', 'Verifica trimestrale']],
    formazione: ['base'],
    norme: ['D.Lgs. 81/08 Titolo III', 'Allegato V'],
    carosello: { cartello: { tipo: 'pericolo', iso7010: 'W001' }, pericolo: 'I ferri sporgenti feriscono.', regola: 'Metti i cappucci sui ferri.' },
  }),
  B({
    id: 'strutture-legno',
    nome: 'Montaggio di strutture e coperture in legno',
    categoria: 'strutture', pericolosita: 'alta',
    descrizione: 'Posa di travi, travetti, capriate, pannelli X-lam e tavolati di coperture e solai in legno, con sollevamento degli elementi.',
    fasi: ['Verifica degli appoggi e dei dormienti', 'Sollevamento e posa delle travi principali', 'Posa della travatura secondaria e del tavolato', 'Fissaggi e ferramenta'],
    rischi: [['Caduta dall\'alto durante la posa della travatura', 3, 4], ['Caduta degli elementi sollevati', 2, 4], ['Ribaltamento di elementi non ancora vincolati', 2, 4], ['Tagli con seghe e chiodatrici', 3, 2]],
    misure: ['Ponteggio perimetrale o parapetti prima di salire sulla struttura', 'Reti anticaduta o linea vita sotto e lungo la travatura', 'Elementi vincolati e controventati man mano che si posano', 'Sollevamenti guidati con funi, nessuno sotto il carico'],
    dpi: ['casco', 'scarpe', 'guanti', 'imbracatura', 'cordino', 'otoprotettori'],
    attrezzature: [['Autogru o gru', 'Verifiche periodiche, operatore abilitato'], ['Sega circolare e chiodatrice', 'Protezioni montate']],
    formazione: ['base', 'anticaduta', 'autogru', 'preposto'],
    norme: ['D.Lgs. 81/08 artt. 111, 115, 148'],
    carosello: { cartello: { tipo: 'obbligo', iso7010: 'M018' }, pericolo: 'Dalle travi si cade.', regola: 'Aggancia l\'imbracatura.' },
  }),
  B({
    id: 'rinforzi-frp',
    nome: 'Rinforzi strutturali con fibre (FRP) e placcaggi',
    categoria: 'strutture', pericolosita: 'media',
    descrizione: 'Rinforzo di travi, pilastri e solai con tessuti e lamine in fibra di carbonio, vetro o acciaio incollati con resine epossidiche, e placcaggi metallici.',
    fasi: ['Preparazione e smussatura degli spigoli', 'Primer e stesura della resina', 'Applicazione dei tessuti o delle lamine', 'Protezione finale'],
    rischi: [['Contatto e inalazione di resine epossidiche', 3, 3], ['Polveri durante la preparazione del supporto', 3, 2], ['Lavoro in quota su trabattelli', 2, 3], ['Sensibilizzazione cutanea', 2, 3]],
    misure: ['Schede di sicurezza delle resine lette prima dell\'uso', 'Locale ventilato durante la stesura', 'Guanti adatti alle resine e maniche lunghe', 'Molatura con aspirazione'],
    dpi: ['guanti_chimici', 'occhiali', 'semimaschera_a', 'ffp3', 'scarpe'],
    attrezzature: [['Smerigliatrice con aspirazione', 'Protezioni e disco adatto'], ['Trabattello', 'Conforme UNI EN 1004']],
    formazione: ['base'],
    norme: ['D.Lgs. 81/08 Titolo IX capo I', 'Regolamento REACH-CLP'],
    carosello: { cartello: { tipo: 'obbligo', iso7010: 'M009' }, pericolo: 'La resina irrita la pelle.', regola: 'Metti i guanti giusti.' },
  }),
  B({
    id: 'consolidamento-murature',
    nome: 'Consolidamento delle murature (cuci-scuci, iniezioni, intonaco armato)',
    categoria: 'strutture', pericolosita: 'media',
    descrizione: 'Cuci-scuci, iniezioni di malte o miscele, perforazioni armate e intonaci armati per il consolidamento di murature esistenti.',
    fasi: ['Puntellatura delle zone interessate', 'Rimozione dell\'intonaco e apertura delle porzioni', 'Ricostruzione o iniezione', 'Rete e intonaco armato'],
    rischi: [['Crollo parziale della muratura durante il cuci-scuci', 2, 4], ['Polveri con silice cristallina', 4, 3], ['Getti di miscela in pressione', 2, 3], ['Rumore e vibrazioni da perforazione', 3, 2]],
    misure: ['Cuci-scuci per piccole porzioni, sempre con puntellatura', 'Nessuno nelle zone sottostanti o adiacenti durante le aperture', 'Pompe di iniezione con manometro e raccordi verificati', 'Bagnare e aspirare'],
    dpi: ['casco', 'scarpe', 'guanti', 'ffp3', 'occhiali', 'otoprotettori'],
    attrezzature: [['Pompa per iniezioni', 'Manometro e raccordi integri'], ['Carotatrice o perforatore', 'Manutenzione e valutazione vibrazioni']],
    formazione: ['base', 'preposto'],
    norme: ['D.Lgs. 81/08 artt. 150-151', 'Titolo IX capo II'],
    carosello: { cartello: { tipo: 'pericolo', iso7010: 'W035' }, pericolo: 'Il muro aperto può cedere.', regola: 'Prima puntella, poi apri.' },
  }),
  // ══ DEMOLIZIONI ══
  B({
    id: 'amianto-friabile',
    nome: 'Bonifica di amianto friabile (confinamento statico e dinamico)',
    categoria: 'demolizioni', pericolosita: 'alta',
    descrizione: 'Rimozione di coibentazioni, intonaci e altri materiali con amianto friabile in area confinata in depressione, con unità di decontaminazione.',
    fasi: ['Piano di lavoro approvato dall\'ASL (art. 256)', 'Confinamento e prove di tenuta', 'Rimozione a umido e insacco', 'Pulizia, monitoraggio e restituibilità'],
    rischi: [['Inalazione di fibre di amianto', 3, 4], ['Contaminazione delle aree esterne al cantiere', 2, 4], ['Stress termico con tute e respiratori', 3, 2], ['Caduta dall\'alto lavorando su ponti mobili', 2, 3]],
    misure: ['Solo impresa iscritta all\'Albo gestori ambientali cat. 10A con piano di lavoro approvato', 'Area confinata in depressione con unità di decontaminazione a 4 stadi', 'Monitoraggio delle fibre aerodisperse durante e dopo i lavori', 'Restituibilità certificata prima di riaprire l\'area alle altre imprese'],
    dpi: ['autorespiratore', 'tuta_monouso', 'guanti', 'stivali'],
    attrezzature: [['Estrattori con filtri assoluti', 'Verifica dei filtri e della depressione'], ['Unità di decontaminazione', 'Controllo giornaliero']],
    formazione: ['amianto', 'preposto'],
    norme: ['D.Lgs. 81/08 Titolo IX capo III', 'D.M. 6/9/1994'],
    carosello: { cartello: { tipo: 'divieto', iso7010: 'P004' }, pericolo: 'L\'amianto fa ammalare.', regola: 'Entra solo se autorizzato.' },
  }),
  // ══ SOLLEVAMENTI ══
  B({
    id: 'montacarichi-argani',
    nome: 'Montacarichi, argani e piattaforme di carico',
    categoria: 'sollevamenti', pericolosita: 'media',
    descrizione: 'Installazione e uso di montacarichi da cantiere, argani a bandiera su ponteggio e piazzole di carico per il sollevamento dei materiali ai piani.',
    fasi: ['Installazione e verifica degli ancoraggi', 'Delimitazione della zona di carico a terra', 'Sollevamento dei materiali', 'Smontaggio'],
    rischi: [['Caduta del carico sollevato', 2, 4], ['Caduta dall\'alto dalla piazzola di carico', 2, 4], ['Ribaltamento dell\'argano per ancoraggio insufficiente', 2, 3], ['Schiacciamento nella zona a terra', 2, 3]],
    misure: ['Argani e montacarichi installati secondo il fabbricante, con verifica degli ancoraggi', 'Zona di carico a terra delimitata, nessuno sotto il carico', 'Piazzole ai piani con parapetto e cancelletto', 'Portata massima esposta e rispettata'],
    dpi: ['casco', 'scarpe', 'guanti', 'gilet'],
    attrezzature: [['Argano a bandiera', 'Verifica trimestrale funi e ganci'], ['Montacarichi da cantiere', 'Verifica periodica (Allegato VII)']],
    formazione: ['base'],
    norme: ['D.Lgs. 81/08 artt. 71, 125', 'Allegato VII'],
    carosello: { cartello: { tipo: 'pericolo', iso7010: 'W015' }, pericolo: 'Il carico può cadere.', regola: 'Non stare sotto il carico.' },
  }),
  // ══ FINITURE ══
  B({
    id: 'rivestimenti-facciata',
    nome: 'Rivestimenti di facciata e facciate ventilate',
    categoria: 'finiture', pericolosita: 'alta',
    descrizione: 'Posa di sottostrutture metalliche e lastre di rivestimento (pietra, gres, compositi, metallo) su facciate, lavorando da ponteggio o piattaforma.',
    fasi: ['Tracciamento e foratura per gli staffaggi', 'Montaggio della sottostruttura', 'Sollevamento e posa delle lastre', 'Sigillature e finiture'],
    rischi: [['Caduta dall\'alto dal ponteggio o dalla piattaforma', 2, 4], ['Caduta di lastre durante il sollevamento', 2, 4], ['Tagli con le lastre e gli utensili', 3, 2], ['Polveri durante il taglio delle lastre', 3, 3]],
    misure: ['Lavoro da ponteggio completo o PLE, mai da scale', 'Lastre sollevate con ventose o argano, area sottostante delimitata', 'Taglio ad umido o con aspirazione', 'Lastre stoccate in verticale su cavalletti'],
    dpi: ['casco', 'scarpe', 'guanti', 'occhiali', 'ffp3'],
    attrezzature: [['Ventose per lastre', 'Verifica della tenuta'], ['Taglierina o flessibile ad acqua', 'Protezioni e disco adatto']],
    formazione: ['base', 'anticaduta'],
    norme: ['D.Lgs. 81/08 artt. 122, 148'],
    carosello: { cartello: { tipo: 'pericolo', iso7010: 'W035' }, pericolo: 'La lastra può cadere.', regola: 'Solleva con le ventose.' },
  }),
  B({
    id: 'sabbiatura',
    nome: 'Sabbiatura e pulizia abrasiva delle superfici',
    categoria: 'finiture', pericolosita: 'alta',
    descrizione: 'Pulizia di superfici in muratura, calcestruzzo o metallo con getto di abrasivo, a secco o a umido, e raccolta dei residui.',
    fasi: ['Confinamento dell\'area con teli', 'Sabbiatura', 'Aspirazione e raccolta degli abrasivi', 'Pulizia finale'],
    rischi: [['Inalazione di polveri e silice cristallina', 4, 3], ['Getto abrasivo su persone', 2, 4], ['Rumore elevato', 4, 2], ['Rimozione di vernici con piombo o altre sostanze', 2, 3]],
    misure: ['Abrasivi senza silice libera e, dove possibile, sabbiatura a umido', 'Area confinata e interdetta alle altre imprese', 'Operatore con casco ventilato e aria respirabile', 'Analisi delle vernici prima di rimuoverle'],
    dpi: ['autorespiratore', 'tuta_monouso', 'guanti', 'otoprotettori', 'scarpe'],
    attrezzature: [['Sabbiatrice', 'Integrità della manichetta e uomo presente'], ['Compressore', 'Verifica del serbatoio']],
    formazione: ['base', 'preposto'],
    norme: ['D.Lgs. 81/08 Titolo VIII capo II', 'Titolo IX capo II'],
    carosello: { cartello: { tipo: 'obbligo', iso7010: 'M017' }, pericolo: 'La polvere di sabbia fa male.', regola: 'Usa il casco ad aria.' },
  }),
  B({
    id: 'porte-falegnameria',
    nome: 'Posa di porte interne e opere di falegnameria',
    categoria: 'finiture', pericolosita: 'media',
    descrizione: 'Posa di controtelai, porte interne, battiscopa, arredi fissi e opere in legno, con taglio e rifinitura in cantiere.',
    fasi: ['Posa dei controtelai', 'Montaggio delle porte e delle ferramenta', 'Battiscopa e finiture', 'Pulizia'],
    rischi: [['Tagli con seghe e utensili', 3, 2], ['Polveri di legno', 3, 2], ['Movimentazione manuale di porte e pannelli', 2, 2], ['Rumore', 2, 2]],
    misure: ['Seghe con protezioni e spingipezzo', 'Taglio con aspirazione', 'Porte movimentate in due', 'Postazione di taglio fuori dai percorsi'],
    dpi: ['scarpe', 'guanti', 'occhiali', 'ffp2', 'otoprotettori'],
    attrezzature: [['Troncatrice o sega circolare', 'Protezioni montate'], ['Avvitatore e pistola sparachiodi', 'Integrità']],
    formazione: ['base'],
    norme: ['D.Lgs. 81/08 Titolo III'],
    carosello: { cartello: { tipo: 'obbligo', iso7010: 'M004' }, pericolo: 'Le schegge colpiscono gli occhi.', regola: 'Metti gli occhiali.' },
  }),
  B({
    id: 'levigatura-pavimenti',
    nome: 'Levigatura e trattamento di pavimenti',
    categoria: 'finiture', pericolosita: 'media',
    descrizione: 'Levigatura e lucidatura di pavimenti in legno, marmo, graniglia o cemento, e trattamenti con vernici, oli o resine.',
    fasi: ['Levigatura grossa e fine', 'Aspirazione delle polveri', 'Stesura di vernici, oli o resine', 'Asciugatura con locale chiuso al passaggio'],
    rischi: [['Polveri di legno o con silice', 3, 3], ['Inalazione di vapori di vernici e solventi', 3, 3], ['Incendio di polveri e stracci impregnati', 2, 3], ['Rumore e vibrazioni', 3, 2]],
    misure: ['Levigatrici con aspirazione', 'Locali ventilati e nessuna fiamma durante i trattamenti', 'Stracci impregnati in contenitori metallici chiusi', 'Locale interdetto alle altre imprese fino all\'asciugatura'],
    dpi: ['scarpe', 'guanti_chimici', 'semimaschera_a', 'ffp3', 'otoprotettori', 'ginocchiere'],
    attrezzature: [['Levigatrice', 'Aspirazione e cavo integri'], ['Aspiratore industriale', 'Filtri puliti']],
    formazione: ['base'],
    norme: ['D.Lgs. 81/08 Titolo IX capo I', 'Titolo VIII capo II'],
    carosello: { cartello: { tipo: 'obbligo', iso7010: 'M017' }, pericolo: 'I vapori della vernice fanno male.', regola: 'Metti la maschera e arieggia.' },
  }),
  // ══ IMPIANTI ══
  B({
    id: 'impianti-climatizzazione',
    nome: 'Impianti di climatizzazione e ventilazione',
    categoria: 'impianti', pericolosita: 'media',
    descrizione: 'Posa di canalizzazioni, unità interne ed esterne, linee frigorifere e condensa; sollevamento delle macchine in copertura o in facciata.',
    fasi: ['Staffaggi e forature', 'Posa delle canalizzazioni e delle linee', 'Sollevamento e posa delle unità esterne', 'Carica del gas e collaudo'],
    rischi: [['Caduta dall\'alto lavorando su trabattelli, scale o in copertura', 2, 4], ['Caduta delle macchine durante il sollevamento', 2, 4], ['Contatto con gas refrigeranti', 2, 3], ['Tagli con lamiere dei canali', 3, 2]],
    misure: ['Lavori in quota da trabattello o PLE, in copertura con parapetti o linea vita', 'Sollevamenti con mezzi idonei, area sottostante delimitata', 'Gas refrigeranti maneggiati da personale certificato F-gas', 'Guanti contro i tagli per i canali'],
    dpi: ['casco', 'scarpe', 'guanti', 'occhiali', 'imbracatura', 'cordino'],
    attrezzature: [['Trabattello', 'Conforme UNI EN 1004'], ['Gruppo di recupero e bombole del gas', 'Integrità e bombole fissate']],
    formazione: ['base', 'anticaduta'],
    norme: ['D.Lgs. 81/08 artt. 111, 113', 'Reg. UE 2024/573 (F-gas)'],
    carosello: { cartello: { tipo: 'pericolo', iso7010: 'W015' }, pericolo: 'La macchina appesa può cadere.', regola: 'Non stare sotto il carico.' },
  }),
  B({
    id: 'impianti-antincendio',
    nome: 'Impianti antincendio (idranti, sprinkler, rivelazione)',
    categoria: 'impianti', pericolosita: 'media',
    descrizione: 'Posa di reti idranti, impianti sprinkler, rivelazione fumi e allarme, porte tagliafuoco e compartimentazioni.',
    fasi: ['Staffaggi e tubazioni', 'Raccordi, saldature o filettature', 'Posa di sensori, centrali e cablaggi', 'Prove di tenuta e collaudo'],
    rischi: [['Caduta dall\'alto lavorando a soffitto', 2, 3], ['Ustioni e incendio durante le saldature', 2, 3], ['Polveri durante le forature', 3, 2], ['Movimentazione di tubazioni pesanti', 3, 2]],
    misure: ['Lavori a soffitto da trabattello o PLE', 'Saldature con permesso di lavoro a caldo ed estintore vicino', 'Forature con aspirazione', 'Tubi pesanti movimentati in due o con mezzi'],
    dpi: ['casco', 'scarpe', 'guanti', 'occhiali', 'ffp2'],
    attrezzature: [['Filettatrice o saldatrice', 'Protezioni e cavi integri'], ['PLE o trabattello', 'Verifiche periodiche']],
    formazione: ['base', 'ple'],
    norme: ['D.Lgs. 81/08 Titolo III', 'D.M. 1/9/2021'],
    carosello: { cartello: { tipo: 'pericolo', iso7010: 'W021' }, pericolo: 'La fiamma dà fuoco.', regola: 'Tieni l\'estintore vicino.' },
  }),
  B({
    id: 'colonne-scarico',
    nome: 'Rifacimento di colonne di scarico e reti fognarie interne',
    categoria: 'impianti', pericolosita: 'media',
    descrizione: 'Sostituzione di colonne di scarico, braghe e collettori interni, in cavedi o in facciata, con smontaggio delle tubazioni esistenti.',
    fasi: ['Svuotamento e interruzione degli scarichi', 'Smontaggio delle tubazioni esistenti', 'Posa delle nuove colonne e dei collettori', 'Prova di tenuta'],
    rischi: [['Contatto con liquami e rischio biologico', 3, 3], ['Caduta dall\'alto in cavedi o da ponteggio', 2, 4], ['Vecchie tubazioni in cemento-amianto', 1, 4], ['Tagli e schiacciamenti', 3, 2]],
    misure: ['Scarichi interrotti e segnalati agli occupanti', 'Guanti impermeabili e lavaggio delle mani', 'Tubazioni sospette di amianto: verifica prima di toccarle', 'Cavedi protetti contro la caduta'],
    dpi: ['scarpe', 'guanti_chimici', 'occhiali', 'ffp2', 'casco'],
    attrezzature: [['Tagliatubi e smerigliatrice', 'Protezioni montate'], ['Ponte su ruote o ponteggio', 'Conforme e completo di parapetti']],
    formazione: ['base'],
    norme: ['D.Lgs. 81/08 Titolo X', 'Titolo IX capo III'],
    carosello: { cartello: { tipo: 'obbligo', iso7010: 'M009' }, pericolo: 'Nei tubi ci sono germi.', regola: 'Metti i guanti.' },
  }),
  // ══ RISCHIO ELETTRICO ══
  B({
    id: 'impianti-speciali',
    nome: 'Impianti speciali (dati, TV, citofoni, allarme, videosorveglianza)',
    categoria: 'elettrico', pericolosita: 'media',
    descrizione: 'Posa di cavi, prese e apparati per reti dati, antenne, citofonia, antintrusione e videosorveglianza.',
    fasi: ['Posa di tubi e canaline', 'Infilaggio dei cavi', 'Montaggio degli apparati', 'Collaudo'],
    rischi: [['Contatto con linee elettriche adiacenti', 2, 3], ['Caduta da scale o trabattelli', 2, 3], ['Lavoro sulle antenne in copertura', 1, 4], ['Polveri durante le tracce', 3, 2]],
    misure: ['Verifica dell\'assenza di tensione nei tubi condivisi', 'Scale e trabattelli conformi; in copertura con linea vita', 'Tracce con aspirazione'],
    dpi: ['scarpe', 'guanti', 'occhiali', 'ffp2'],
    attrezzature: [['Scale portatili', 'Conformi UNI EN 131'], ['Scanalatrice', 'Aspirazione e cavo integri']],
    formazione: ['base'],
    norme: ['D.Lgs. 81/08 artt. 80-83', 'CEI 11-27'],
    carosello: { cartello: { tipo: 'pericolo', iso7010: 'W012' }, pericolo: 'Nei tubi può esserci corrente.', regola: 'Controlla prima di infilare.' },
  }),
  // ══ ALLESTIMENTO ══ F-307: richiesta della coordinatrice nella seconda prova
  B({
    id: 'impianto-idrico-cantiere',
    nome: 'Impianto idrico di cantiere',
    categoria: 'allestimento', pericolosita: 'media',
    descrizione: 'Allaccio provvisorio alla rete idrica, posa delle tubazioni di cantiere, punti di prelievo per lavorazioni e servizi igienici, scarichi; rimozione a fine lavori.',
    fasi: ['Allaccio al contatore o alla rete con autorizzazione del gestore', 'Posa delle tubazioni a vista o in traccia provvisoria', 'Punti di prelievo, lavaggio attrezzi e servizi igienici', 'Rimozione e ripristino a fine lavori'],
    rischi: [['Scivolamento su superfici bagnate e perdite', 3, 2], ['Inciampo su tubazioni a terra', 3, 2], ['Contatto tra acqua e parti elettriche', 1, 4], ['Tagli durante il taglio dei tubi', 2, 2]],
    misure: ['Tubazioni lontane da quadri, prese e cavi elettrici, o protette', 'Tubi sollevati o protetti nei passaggi pedonali e carrabili', 'Perdite riparate subito; zone bagnate segnalate', 'Acqua dei servizi igienici potabile o segnalata come non potabile', 'Scarichi convogliati, mai sulla via pubblica'],
    dpi: ['scarpe', 'guanti'],
    attrezzature: [['Tubazioni e raccordi di cantiere', 'Integrità e fissaggio'], ['Tagliatubi e utensili manuali', 'Lame integre']],
    formazione: ['base'],
    norme: ['D.Lgs. 81/08 Allegato XIII', 'Allegato XV punto 2.2.2'],
    carosello: { cartello: { tipo: 'pericolo', iso7010: 'W011' }, pericolo: 'Dove c\'è acqua si scivola.', regola: 'Segnala subito le perdite.' },
    sostituisce: [], // nel vecchio catalogo POS l'impianto idrico resta mappato su allestimento-cantiere
  }),
  // ══ ESTERNI ══
  B({
    id: 'recinzioni-muretti',
    nome: 'Recinzioni definitive, muretti e cordoli',
    categoria: 'esterni', pericolosita: 'media',
    descrizione: 'Realizzazione di cordoli e muretti di recinzione, posa di pannelli, cancellate e paletti, anche lungo strade aperte al traffico.',
    fasi: ['Scavo e getto dei cordoli', 'Posa dei paletti e dei pannelli', 'Montaggio dei cancelli', 'Ripristini'],
    rischi: [['Investimento da veicoli lungo strade aperte', 2, 4], ['Movimentazione di pannelli e cancelli', 3, 2], ['Contatto con calcestruzzo e cemento', 3, 2], ['Tagli e schiacciamenti', 3, 2]],
    misure: ['Lungo strada: segnaletica temporanea e area delimitata (D.M. 10/7/2002)', 'Cancelli pesanti posati con mezzi di sollevamento', 'Guanti contro il cemento', 'Pannelli movimentati in due'],
    dpi: ['casco', 'scarpe', 'guanti', 'gilet'],
    attrezzature: [['Betoniera', 'Protezioni e cavo integri'], ['Saldatrice per i fissaggi', 'Cavi e pinza integri']],
    formazione: ['base', 'segnaletica'],
    norme: ['D.Lgs. 81/08 Titolo III', 'D.I. 22/01/2019'],
    carosello: { cartello: { tipo: 'obbligo', iso7010: 'M015' }, pericolo: 'Sulla strada passano le auto.', regola: 'Metti il gilet giallo.' },
  }),
];

module.exports = { SCHEDE_EXTRA };
